* tar
#+begin_example
    tar 是 Linux/Unix 下常用的归档工具，可用于打包和解压缩文件。以下是 tar 的常见用法：
#+end_example
** 创建压缩包
#+begin_example
    tar -cvf archive.tar file1 file2 dir1

        -c：创建新的归档文件
        -v：显示详细信息
        -f：指定归档文件名
#+end_example
** 创建并压缩归档文件
#+begin_example
    tar -czvf archive.tar.gz file1 file2 dir1
    tar -cjvf archive.tar.bz2 file1 file2 dir1
    tar -cJvf archive.tar.xz file1 file2 dir1

        -z：使用 gzip 压缩（.tar.gz）
        -j：使用 bzip2 压缩（.tar.bz2）
        -J：使用 xz 压缩（.tar.xz）
#+end_example
** 解压缩归档文件
#+begin_example
    tar -xvf archive.tar
    tar -xzvf archive.tar.gz
    tar -xjvf archive.tar.bz2
    tar -xJvf archive.tar.xz

        -x：解压缩文件
#+end_example
** 查看归档内容
#+begin_example
    tar -tvf archive.tar
    tar -tzvf archive.tar.gz
#+end_example
** 解压到指定目录
#+begin_example
    tar -xvf archive.tar -C /target/directory
#+end_example
** 添加文件到已有归档
#+begin_example
    tar -rvf archive.tar newfile
        -r：追加文件（仅适用于未压缩的 .tar）
#+end_example
** 从归档删除文件
#+begin_example
    tar --delete -f archive.tar file1
    （注意：不能删除压缩格式的 tar.gz、tar.bz2）
#+end_example
** 提取特定文件
#+begin_example
    tar -xvf archive.tar file1
#+end_example
** 使用管道传输
#+begin_example
    打包后通过 gzip 压缩：
    tar -cvf - dir1 | gzip > archive.tar.gz
    解压：
    gzip -dc archive.tar.gz | tar -xvf -
#+end_example
* lsblk
#+begin_src
可以使用 lsblk 命令加上 -f 选项，它会显示文件系统类型。执行以下命令：
lsblk -f
输出的结果中，FSTYPE 列会显示文件系统类型，如果是 NTFS，则会显示 ntfs。
#+end_src
* du
** 显示当前目录文件和文件夹大小
#+begin_src sh
    du -h --max-depth=1
#+end_src
** 按大小排序后显示
#+begin_src sh
    du --max-depth=1 | sort -nr
#+end_src

* cp
#+begin_example
cp -r 和 cp -R 基本等价，都是递归复制目录。
例如：
cp -r dir1 dir2cp -R dir1 dir2
都会把 dir1 整个目录及其子目录、文件复制到 dir2。
区别：


POSIX 标准推荐 -R


GNU/Linux 下通常 -r 和 -R 行为一样


某些老 Unix 系统里：


-r 可能对特殊文件（设备文件、符号链接等）处理不规范


-R 更标准、更安全




现代 Linux（如 Ubuntu、Debian）：


实际几乎没区别


日常可随便用


更推荐：


cp -R
另外常见组合：
cp -a
等价于：
cp -dR --preserve=all
用于：


保留权限


保留时间戳


保留符号链接


保留属主


做目录完整复制时通常更推荐：
cp -a src dst
#+end_example
* w
#+begin_example
Linux w命令用于显示目前登入系统的用户信息。
执行这项指令可得知目前登入系统的用户有哪些人，以及他们正在执行的程序。
单独执行 w 指令会显示所有的用户，您也可指定用户名称，仅显示某位用户的相关信息。
语法
w [-fhlsuV][用户名称]
#+end_example
** 参数说明：
#+begin_example
    -f 　开启或关闭显示用户从何处登入系统。
    -h 　不显示各栏位的标题信息列。
    -l 　使用详细格式列表，此为预设值。
    -s 　使用简洁格式列表，不显示用户登入时间，终端机阶段作业和程序所耗费的CPU时间。
    -u 　忽略执行程序的名称，以及该程序耗费CPU时间的信息。
    -V 　显示版本信息。
#+end_example
** 实例
#+begin_example
- 显示当前用户

# w  // 显示当前用户登录信息及执行的命令
19:50:14 up 9:27, 4 users, load average: 0.31, 0.26, 0.18
USER   TTY   FROM       LOGIN@  IDLE  JCPU  PCPU WHAT
root   tty7   :0        Thu12  31:39m 10:10  0.60s gnome-session
root   pts/0  :0.0       17:09  2:18m 15.26s 0.15s bash
root   pts/1  192.168.1.17   18:51  1.00s 1.24s 0.14s -bash
root   pts/2  192.168.1.17   19:48  60.00s 0.05s 0.05s -bash

- 不显示登录位置

w -f
19:53:59 up 9:31, 4 users, load average: 0.05, 0.16, 0.15
USER   TTY    LOGIN@  IDLE  JCPU  PCPU WHAT
root   tty7   Thu12  31:43m 10:10  0.60s gnome-session
root   pts/0   17:09  2:21m 15.26s 0.15s bash
root   pts/1   18:51  0.00s 1.04s 0.14s -bash
root   pts/2   19:48  4:45  0.05s 0.05s -bash

- 以精简模式显示

w -s
19:54:37 up 9:31, 4 users, load average: 0.24, 0.19, 0.16
USER   TTY   FROM        IDLE WHAT
root   tty7   :0        31:43m gnome-session
root   pts/0  :0.0       2:22m bash
root   pts/1  192.168.1.17   0.00s -bash
root   pts/2  192.168.1.17   5:23 -bash

- 不显示标题

w -h
root   tty7   :0        Thu12  31:44m 10:10  0.60s gnome-session
root   pts/0  :0.0       17:09  2:23m 15.26s 0.15s bash
root   pts/1  192.168.1.17   18:51  0.00s 1.05s 0.14s -bash
root   pts/2  192.168.1.17   19:48  5:54  0.05s 0.05s -bash
#+end_example
* rg
** help
ripgrep 14.1.1
Andrew Gallant <jamslam@gmail.com>

ripgrep (rg) recursively searches the current directory for lines matching
a regex pattern. By default, ripgrep will respect gitignore rules and
automatically skip hidden files/directories and binary files.

Use -h for short descriptions and --help for more details.

Project home page: https://github.com/BurntSushi/ripgrep

USAGE:
    rg [OPTIONS] PATTERN [PATH ...]
    rg [OPTIONS] -e PATTERN ... [PATH ...]
    rg [OPTIONS] -f PATTERNFILE ... [PATH ...]
    rg [OPTIONS] --files [PATH ...]
    rg [OPTIONS] --type-list
    command | rg [OPTIONS] PATTERN
    rg [OPTIONS] --help
    rg [OPTIONS] --version

POSITIONAL ARGUMENTS:
    <PATTERN>
        A regular expression used for searching. To match a pattern beginning
        with a dash, use the -e/--regexp flag.

        For example, to search for the literal '-foo', you can use this flag:

            rg -e -foo

        You can also use the special '--' delimiter to indicate that no more
        flags will be provided. Namely, the following is equivalent to the
        above:

            rg -- -foo

    <PATH>...
        A file or directory to search. Directories are searched recursively.
        File paths specified on the command line override glob and ignore
        rules.

INPUT OPTIONS:
    -e PATTERN, --regexp=PATTERN
        A pattern to search for. This option can be provided multiple times,
        where all patterns given are searched, in addition to any patterns
        provided by -f/--file. Lines matching at least one of the provided
        patterns are printed. This flag can also be used when searching for
        patterns that start with a dash.

        For example, to search for the literal -foo:

            rg -e -foo

        You can also use the special -- delimiter to indicate that no more
        flags will be provided. Namely, the following is equivalent to the
        above:

            rg -- -foo

        When -f/--file or -e/--regexp is used, then ripgrep treats all
        positional arguments as files or directories to search.

    -f PATTERNFILE, --file=PATTERNFILE
        Search for patterns from the given file, with one pattern per line.
        When this flag is used multiple times or in combination with the
        -e/--regexp flag, then all patterns provided are searched. Empty
        pattern lines will match all input lines, and the newline is not
        counted as part of the pattern.

        A line is printed if and only if it matches at least one of the
        patterns.

        When PATTERNFILE is -, then stdin will be read for the patterns.

        When -f/--file or -e/--regexp is used, then ripgrep treats all
        positional arguments as files or directories to search.

    --pre=COMMAND
        For each input PATH, this flag causes ripgrep to search the standard
        output of COMMAND PATH instead of the contents of PATH. This option
        expects the COMMAND program to either be a path or to be available in
        your PATH. Either an empty string COMMAND or the --no-pre flag will
        disable this behavior.

        WARNING: When this flag is set, ripgrep will unconditionally spawn a
        process for every file that is searched. Therefore, this can incur an
        unnecessarily large performance penalty if you don't otherwise need the
        flexibility offered by this flag. One possible mitigation to this is to
        use the --pre-glob flag to limit which files a preprocessor is run
        with.

        A preprocessor is not run when ripgrep is searching stdin.

        When searching over sets of files that may require one of several
        preprocessors, COMMAND should be a wrapper program which first
        classifies PATH based on magic numbers/content or based on the PATH
        name and then dispatches to an appropriate preprocessor. Each COMMAND
        also has its standard input connected to PATH for convenience.

        For example, a shell script for COMMAND might look like:

            case "$1" in
            *.pdf)
                exec pdftotext "$1" -
                ;;
            *)
                case $(file "$1") in
                *Zstandard*)
                    exec pzstd -cdq
                    ;;
                *)
                    exec cat
                    ;;
                esac
                ;;
            esac

        The above script uses pdftotext to convert a PDF file to plain text.
        For all other files, the script uses the file utility to sniff the type
        of the file based on its contents. If it is a compressed file in the
        Zstandard format, then pzstd is used to decompress the contents to
        stdout.

        This overrides the -z/--search-zip flag.

    --pre-glob=GLOB
        This flag works in conjunction with the --pre flag. Namely, when one or
        more --pre-glob flags are given, then only files that match the given
        set of globs will be handed to the command specified by the --pre flag.
        Any non-matching files will be searched without using the preprocessor
        command.

        This flag is useful when searching many files with the --pre flag.
        Namely, it provides the ability to avoid process overhead for files
        that don't need preprocessing. For example, given the following shell
        script, pre-pdftotext:

            #!/bin/sh
            pdftotext "$1" -

        then it is possible to use --pre pre-pdftotext --pre-glob '*.pdf' to
        make it so ripgrep only executes the pre-pdftotext command on files
        with a .pdf extension.

        Multiple --pre-glob flags may be used. Globbing rules match gitignore
        globs. Precede a glob with a ! to exclude it.

        This flag has no effect if the --pre flag is not used.

    -z, --search-zip
        This flag instructs ripgrep to search in compressed files. Currently
        gzip, bzip2, xz, LZ4, LZMA, Brotli and Zstd files are supported. This
        option expects the decompression binaries (such as gzip) to be
        available in your PATH. If the required binaries are not found, then
        ripgrep will not emit an error messages by default. Use the --debug
        flag to see more information.

        Note that this flag does not make ripgrep search archive formats as
        directory trees. It only makes ripgrep detect compressed files and then
        decompress them before searching their contents as it would any other
        file.

        This overrides the --pre flag.

        This flag can be disabled with --no-search-zip.

SEARCH OPTIONS:
    -s, --case-sensitive
        Execute the search case sensitively. This is the default mode.

        This is a global option that applies to all patterns given to ripgrep.
        Individual patterns can still be matched case insensitively by using
        inline regex flags. For example, (?i)abc will match abc case
        insensitively even when this flag is used.

        This flag overrides the -i/--ignore-case and -S/--smart-case flags.

    --crlf
        When enabled, ripgrep will treat CRLF (\r\n) as a line terminator
        instead of just \n.

        Principally, this permits the line anchor assertions ^ and $ in regex
        patterns to treat CRLF, CR or LF as line terminators instead of just
        LF. Note that they will never match between a CR and a LF. CRLF is
        treated as one single line terminator.

        When using the default regex engine, CRLF support can also be enabled
        inside the pattern with the R flag. For example, (?R:$) will match just
        before either CR or LF, but never between CR and LF.

        This flag overrides --null-data.

        This flag can be disabled with --no-crlf.

    --dfa-size-limit=NUM+SUFFIX?
        The upper size limit of the regex DFA. The default limit is something
        generous for any single pattern or for many smallish patterns. This
        should only be changed on very large regex inputs where the (slower)
        fallback regex engine may otherwise be used if the limit is reached.

        The input format accepts suffixes of K, M or G which correspond to
        kilobytes, megabytes and gigabytes, respectively. If no suffix is
        provided the input is treated as bytes.

    -E ENCODING, --encoding=ENCODING
        Specify the text encoding that ripgrep will use on all files searched.
        The default value is auto, which will cause ripgrep to do a best effort
        automatic detection of encoding on a per-file basis. Automatic
        detection in this case only applies to files that begin with a UTF-8 or
        UTF-16 byte-order mark (BOM). No other automatic detection is
        performed. One can also specify none which will then completely disable
        BOM sniffing and always result in searching the raw bytes, including a
        BOM if it's present, regardless of its encoding.

        Other supported values can be found in the list of labels here:
        https://encoding.spec.whatwg.org/#concept-encoding-get.

        For more details on encoding and how ripgrep deals with it, see
        GUIDE.md.

        The encoding detection that ripgrep uses can be reverted to its
        automatic mode via the --no-encoding flag.

    --engine=ENGINE
        Specify which regular expression engine to use. When you choose a regex
        engine, it applies that choice for every regex provided to ripgrep
        (e.g., via multiple -e/--regexp or -f/--file flags).

        Accepted values are default, pcre2, or auto.

        The default value is default, which is usually the fastest and should
        be good for most use cases. The pcre2 engine is generally useful when
        you want to use features such as look-around or backreferences. auto
        will dynamically choose between supported regex engines depending on
        the features used in a pattern on a best effort basis.

        Note that the pcre2 engine is an optional ripgrep feature. If PCRE2
        wasn't included in your build of ripgrep, then using this flag will
        result in ripgrep printing an error message and exiting.

        This overrides previous uses of the -P/--pcre2 and --auto-hybrid-regex
        flags.

    -F, --fixed-strings
        Treat all patterns as literals instead of as regular expressions. When
        this flag is used, special regular expression meta characters such as
        .(){}*+ should not need be escaped.

        This flag can be disabled with --no-fixed-strings.

    -i, --ignore-case
        When this flag is provided, all patterns will be searched case
        insensitively. The case insensitivity rules used by ripgrep's default
        regex engine conform to Unicode's "simple" case folding rules.

        This is a global option that applies to all patterns given to ripgrep.
        Individual patterns can still be matched case sensitively by using
        inline regex flags. For example, (?-i)abc will match abc case
        sensitively even when this flag is used.

        This flag overrides -s/--case-sensitive and -S/--smart-case.

    -v, --invert-match
        This flag inverts matching. That is, instead of printing lines that
        match, ripgrep will print lines that don't match.

        Note that this only inverts line-by-line matching. For example,
        combining this flag with -l/--files-with-matches will emit files that
        contain any lines that do not match the patterns given. That's not the
        same as, for example, --files-without-match, which will emit files that
        do not contain any matching lines.

        This flag can be disabled with --no-invert-match.

    -x, --line-regexp
        When enabled, ripgrep will only show matches surrounded by line
        boundaries. This is equivalent to surrounding every pattern with ^ and
        $. In other words, this only prints lines where the entire line
        participates in a match.

        This overrides the -w/--word-regexp flag.

    -m NUM, --max-count=NUM
        Limit the number of matching lines per file searched to NUM.

        Note that 0 is a legal value but not likely to be useful. When used,
        ripgrep won't search anything.

    --mmap
        When enabled, ripgrep will search using memory maps when possible. This
        is enabled by default when ripgrep thinks it will be faster.

        Memory map searching cannot be used in all circumstances. For example,
        when searching virtual files or streams likes stdin. In such cases,
        memory maps will not be used even when this flag is enabled.

        Note that ripgrep may abort unexpectedly when memory maps are used if
        it searches a file that is simultaneously truncated. Users can opt out
        of this possibility by disabling memory maps.

        This flag can be disabled with --no-mmap.

    -U, --multiline
        This flag enable searching across multiple lines.

        When multiline mode is enabled, ripgrep will lift the restriction that
        a match cannot include a line terminator. For example, when multiline
        mode is not enabled (the default), then the regex \p{any} will match
        any Unicode codepoint other than \n. Similarly, the regex \n is
        explicitly forbidden, and if you try to use it, ripgrep will return an
        error. However, when multiline mode is enabled, \p{any} will match any
        Unicode codepoint, including \n, and regexes like \n are permitted.

        An important caveat is that multiline mode does not change the match
        semantics of .. Namely, in most regex matchers, a . will by default
        match any character other than \n, and this is true in ripgrep as well.
        In order to make . match \n, you must enable the "dot all" flag inside
        the regex. For example, both (?s). and (?s:.) have the same semantics,
        where . will match any character, including \n. Alternatively, the
        --multiline-dotall flag may be passed to make the "dot all" behavior
        the default. This flag only applies when multiline search is enabled.

        There is no limit on the number of the lines that a single match can
        span.

        WARNING: Because of how the underlying regex engine works, multiline
        searches may be slower than normal line-oriented searches, and they may
        also use more memory. In particular, when multiline mode is enabled,
        ripgrep requires that each file it searches is laid out contiguously in
        memory (either by reading it onto the heap or by memory-mapping it).
        Things that cannot be memory-mapped (such as stdin) will be consumed
        until EOF before searching can begin. In general, ripgrep will only do
        these things when necessary. Specifically, if the -U/--multiline flag
        is provided but the regex does not contain patterns that would match \n
        characters, then ripgrep will automatically avoid reading each file
        into memory before searching it. Nevertheless, if you only care about
        matches spanning at most one line, then it is always better to disable
        multiline mode.

        This overrides the --stop-on-nonmatch flag.

        This flag can be disabled with --no-multiline.

    --multiline-dotall
        This flag enables "dot all" mode in all regex patterns. This causes .
        to match line terminators when multiline searching is enabled. This
        flag has no effect if multiline searching isn't enabled with the
        -U/--multiline flag.

        Normally, a . will match any character except line terminators. While
        this behavior typically isn't relevant for line-oriented matching
        (since matches can span at most one line), this can be useful when
        searching with the -U/--multiline flag. By default, multiline mode runs
        without "dot all" mode enabled.

        This flag is generally intended to be used in an alias or your ripgrep
        config file if you prefer "dot all" semantics by default. Note that
        regardless of whether this flag is used, "dot all" semantics can still
        be controlled via inline flags in the regex pattern itself, e.g.,
        (?s:.) always enables "dot all" whereas (?-s:.) always disables "dot
        all". Moreover, you can use character classes like \p{any} to match any
        Unicode codepoint regardless of whether "dot all" mode is enabled or
        not.

        This flag can be disabled with --no-multiline-dotall.

    --no-unicode
        This flag disables Unicode mode for all patterns given to ripgrep.

        By default, ripgrep will enable "Unicode mode" in all of its regexes.
        This has a number of consequences:

        • . will only match valid UTF-8 encoded Unicode scalar values.

        • Classes like \w, \s, \d are all Unicode aware and much bigger than
        their ASCII only versions.

        • Case insensitive matching will use Unicode case folding.

        • A large array of classes like \p{Emoji} are available. (Although the
        specific set of classes available varies based on the regex engine. In
        general, the default regex engine has more classes available to it.)

        • Word boundaries (\b and \B) use the Unicode definition of a word
        character.

        In some cases it can be desirable to turn these things off. This flag
        will do exactly that. For example, Unicode mode can sometimes have a
        negative impact on performance, especially when things like \w are used
        frequently (including via bounded repetitions like \w{100}) when only
        their ASCII interpretation is needed.

        This flag can be disabled with --unicode.

    --null-data
        Enabling this flag causes ripgrep to use NUL as a line terminator
        instead of the default of \n.

        This is useful when searching large binary files that would otherwise
        have very long lines if \n were used as the line terminator. In
        particular, ripgrep requires that, at a minimum, each line must fit
        into memory. Using NUL instead can be a useful stopgap to keep memory
        requirements low and avoid OOM (out of memory) conditions.

        This is also useful for processing NUL delimited data, such as that
        emitted when using ripgrep's -0/--null flag or find's --print0 flag.

        Using this flag implies -a/--text. It also overrides --crlf.

    -P, --pcre2
        When this flag is present, ripgrep will use the PCRE2 regex engine
        instead of its default regex engine.

        This is generally useful when you want to use features such as
        look-around or backreferences.

        Using this flag is the same as passing --engine=pcre2. Users may
        instead elect to use --engine=auto to ask ripgrep to automatically
        select the right regex engine based on the patterns given. This flag
        and the --engine flag override one another.

        Note that PCRE2 is an optional ripgrep feature. If PCRE2 wasn't
        included in your build of ripgrep, then using this flag will result in
        ripgrep printing an error message and exiting. PCRE2 may also have
        worse user experience in some cases, since it has fewer introspection
        APIs than ripgrep's default regex engine. For example, if you use a \n
        in a PCRE2 regex without the -U/--multiline flag, then ripgrep will
        silently fail to match anything instead of reporting an error
        immediately (like it does with the default regex engine).

        This flag can be disabled with --no-pcre2.

    --regex-size-limit=NUM+SUFFIX?
        The size limit of the compiled regex, where the compiled regex
        generally corresponds to a single object in memory that can match all
        of the patterns provided to ripgrep. The default limit is generous
        enough that most reasonable patterns (or even a small number of them)
        should fit.

        This useful to change when you explicitly want to let ripgrep spend
        potentially much more time and/or memory building a regex matcher.

        The input format accepts suffixes of K, M or G which correspond to
        kilobytes, megabytes and gigabytes, respectively. If no suffix is
        provided the input is treated as bytes.

    -S, --smart-case
        This flag instructs ripgrep to searches case insensitively if the
        pattern is all lowercase. Otherwise, ripgrep will search case
        sensitively.

        A pattern is considered all lowercase if both of the following rules
        hold:

        • First, the pattern contains at least one literal character. For
        example, a\w contains a literal (a) but just \w does not.

        • Second, of the literals in the pattern, none of them are considered
        to be uppercase according to Unicode. For example, foo\pL has no
        uppercase literals but Foo\pL does.

        This overrides the -s/--case-sensitive and -i/--ignore-case flags.

    --stop-on-nonmatch
        Enabling this option will cause ripgrep to stop reading a file once it
        encounters a non-matching line after it has encountered a matching
        line. This is useful if it is expected that all matches in a given file
        will be on sequential lines, for example due to the lines being sorted.

        This overrides the -U/--multiline flag.

    -a, --text
        This flag instructs ripgrep to search binary files as if they were
        text. When this flag is present, ripgrep's binary file detection is
        disabled. This means that when a binary file is searched, its contents
        may be printed if there is a match. This may cause escape codes to be
        printed that alter the behavior of your terminal.

        When binary file detection is enabled, it is imperfect. In general, it
        uses a simple heuristic. If a NUL byte is seen during search, then the
        file is considered binary and searching stops (unless this flag is
        present). Alternatively, if the --binary flag is used, then ripgrep
        will only quit when it sees a NUL byte after it sees a match (or
        searches the entire file).

        This flag overrides the --binary flag.

        This flag can be disabled with --no-text.

    -j NUM, --threads=NUM
        This flag sets the approximate number of threads to use. A value of 0
        (which is the default) causes ripgrep to choose the thread count using
        heuristics.

    -w, --word-regexp
        When enabled, ripgrep will only show matches surrounded by word
        boundaries. This is equivalent to surrounding every pattern with
        \b{start-half} and \b{end-half}.

        This overrides the -x/--line-regexp flag.

    --auto-hybrid-regex
        DEPRECATED. Use --engine instead.

        When this flag is used, ripgrep will dynamically choose between
        supported regex engines depending on the features used in a pattern.
        When ripgrep chooses a regex engine, it applies that choice for every
        regex provided to ripgrep (e.g., via multiple -e/--regexp or -f/--file
        flags).

        As an example of how this flag might behave, ripgrep will attempt to
        use its default finite automata based regex engine whenever the pattern
        can be successfully compiled with that regex engine. If PCRE2 is
        enabled and if the pattern given could not be compiled with the default
        regex engine, then PCRE2 will be automatically used for searching. If
        PCRE2 isn't available, then this flag has no effect because there is
        only one regex engine to choose from.

        In the future, ripgrep may adjust its heuristics for how it decides
        which regex engine to use. In general, the heuristics will be limited
        to a static analysis of the patterns, and not to any specific runtime
        behavior observed while searching files.

        The primary downside of using this flag is that it may not always be
        obvious which regex engine ripgrep uses, and thus, the match semantics
        or performance profile of ripgrep may subtly and unexpectedly change.
        However, in many cases, all regex engines will agree on what
        constitutes a match and it can be nice to transparently support more
        advanced regex features like look-around and backreferences without
        explicitly needing to enable them.

        This flag can be disabled with --no-auto-hybrid-regex.

    --no-pcre2-unicode
        DEPRECATED. Use --no-unicode instead.

        Note that Unicode mode is enabled by default.

        This flag can be disabled with --pcre2-unicode.

FILTER OPTIONS:
    --binary
        Enabling this flag will cause ripgrep to search binary files. By
        default, ripgrep attempts to automatically skip binary files in order
        to improve the relevance of results and make the search faster.

        Binary files are heuristically detected based on whether they contain a
        NUL byte or not. By default (without this flag set), once a NUL: byte
        is seen, ripgrep will stop searching the file. Usually, NUL bytes occur
        in the beginning of most binary files. If a NUL byte occurs after a
        match, then ripgrep will not print the match, stop searching that file,
        and emit a warning that some matches are being suppressed.

        In contrast, when this flag is provided, ripgrep will continue
        searching a file even if a NUL byte is found. In particular, if a NUL
        byte is found then ripgrep will continue searching until either a match
        is found or the end of the file is reached, whichever comes sooner. If
        a match is found, then ripgrep will stop and print a warning saying
        that the search stopped prematurely.

        If you want ripgrep to search a file without any special NUL byte
        handling at all (and potentially print binary data to stdout), then you
        should use the -a/--text flag.

        The --binary flag is a flag for controlling ripgrep's automatic
        filtering mechanism. As such, it does not need to be used when
        searching a file explicitly or when searching stdin. That is, it is
        only applicable when recursively searching a directory.

        When the -u/--unrestricted flag is provided for a third time, then this
        flag is automatically enabled.

        This flag overrides the -a/--text flag.

        This flag can be disabled with --no-binary.

    -L, --follow
        This flag instructs ripgrep to follow symbolic links while traversing
        directories. This behavior is disabled by default. Note that ripgrep
        will check for symbolic link loops and report errors if it finds one.
        ripgrep will also report errors for broken links. To suppress error
        messages, use the --no-messages flag.

        This flag can be disabled with --no-follow.

    -g GLOB, --glob=GLOB
        Include or exclude files and directories for searching that match the
        given glob. This always overrides any other ignore logic. Multiple glob
        flags may be used. Globbing rules match .gitignore globs. Precede a
        glob with a ! to exclude it. If multiple globs match a file or
        directory, the glob given later in the command line takes precedence.

        As an extension, globs support specifying alternatives: "-g'"ab{c,d}*'
        is equivalent to "-g""abc""-g"abd. Empty alternatives like "-g'"ab{,c}'
        are not currently supported. Note that this syntax extension is also
        currently enabled in gitignore files, even though this syntax isn't
        supported by git itself. ripgrep may disable this syntax extension in
        gitignore files, but it will always remain available via the -g/--glob
        flag.

        When this flag is set, every file and directory is applied to it to
        test for a match. For example, if you only want to search in a
        particular directory foo, then "-g"foo is incorrect because foo/bar
        does not match the glob foo. Instead, you should use "-g'"foo/**'.

    --glob-case-insensitive
        Process all glob patterns given with the -g/--glob flag case
        insensitively. This effectively treats -g/--glob as --iglob.

        This flag can be disabled with --no-glob-case-insensitive.

    -., --hidden
        Search hidden files and directories. By default, hidden files and
        directories are skipped. Note that if a hidden file or a directory is
        whitelisted in an ignore file, then it will be searched even if this
        flag isn't provided. Similarly if a hidden file or directory is given
        explicitly as an argument to ripgrep.

        A file or directory is considered hidden if its base name starts with a
        dot character (.). On operating systems which support a "hidden" file
        attribute, like Windows, files with this attribute are also considered
        hidden.

        This flag can be disabled with --no-hidden.

    --iglob=GLOB
        Include or exclude files and directories for searching that match the
        given glob. This always overrides any other ignore logic. Multiple glob
        flags may be used. Globbing rules match .gitignore globs. Precede a
        glob with a ! to exclude it. If multiple globs match a file or
        directory, the glob given later in the command line takes precedence.
        Globs used via this flag are matched case insensitively.

    --ignore-file=PATH
        Specifies a path to one or more gitignore formatted rules files. These
        patterns are applied after the patterns found in .gitignore, .rgignore
        and .ignore are applied and are matched relative to the current working
        directory. Multiple additional ignore files can be specified by using
        this flag repeatedly. When specifying multiple ignore files, earlier
        files have lower precedence than later files.

        If you are looking for a way to include or exclude files and
        directories directly on the command line, then use -g/--glob instead.

    --ignore-file-case-insensitive
        Process ignore files (.gitignore, .ignore, etc.) case insensitively.
        Note that this comes with a performance penalty and is most useful on
        case insensitive file systems (such as Windows).

        This flag can be disabled with --no-ignore-file-case-insensitive.

    -d NUM, --max-depth=NUM
        This flag limits the depth of directory traversal to NUM levels beyond
        the paths given. A value of 0 only searches the explicitly given paths
        themselves.

        For example, rg --max-depth 0 dir/ is a no-op because dir/ will not be
        descended into. rg --max-depth 1 dir/ will search only the direct
        children of dir.

        An alternative spelling for this flag is --maxdepth.

    --max-filesize=NUM+SUFFIX?
        Ignore files larger than NUM in size. This does not apply to
        directories.

        The input format accepts suffixes of K, M or G which correspond to
        kilobytes, megabytes and gigabytes, respectively. If no suffix is
        provided the input is treated as bytes.

        Examples: --max-filesize 50K or --max-filesize 80M.

    --no-ignore
        When set, ignore files such as .gitignore, .ignore and .rgignore will
        not be respected. This implies --no-ignore-dot, --no-ignore-exclude,
        --no-ignore-global, --no-ignore-parent and --no-ignore-vcs.

        This does not imply --no-ignore-files, since --ignore-file is specified
        explicitly as a command line argument.

        When given only once, the -u/--unrestricted flag is identical in
        behavior to this flag and can be considered an alias. However,
        subsequent -u/--unrestricted flags have additional effects.

        This flag can be disabled with --ignore.

    --no-ignore-dot
        Don't respect filter rules from .ignore or .rgignore files.

        This does not impact whether ripgrep will ignore files and directories
        whose names begin with a dot. For that, see the -./--hidden flag. This
        flag also does not impact whether filter rules from .gitignore files
        are respected.

        This flag can be disabled with --ignore-dot.

    --no-ignore-exclude
        Don't respect filter rules from files that are manually configured for
        the repository. For example, this includes git's .git/info/exclude.

        This flag can be disabled with --ignore-exclude.

    --no-ignore-files
        When set, any --ignore-file flags, even ones that come after this flag,
        are ignored.

        This flag can be disabled with --ignore-files.

    --no-ignore-global
        Don't respect filter rules from ignore files that come from "global"
        sources such as git's core.excludesFile configuration option (which
        defaults to $HOME/.config/git/ignore).

        This flag can be disabled with --ignore-global.

    --no-ignore-parent
        When this flag is set, filter rules from ignore files found in parent
        directories are not respected. By default, ripgrep will ascend the
        parent directories of the current working directory to look for any
        applicable ignore files that should be applied. In some cases this may
        not be desirable.

        This flag can be disabled with --ignore-parent.

    --no-ignore-vcs
        When given, filter rules from source control ignore files (e.g.,
        .gitignore) are not respected. By default, ripgrep respects git's
        ignore rules for automatic filtering. In some cases, it may not be
        desirable to respect the source control's ignore rules and instead only
        respect rules in .ignore or .rgignore.

        This flag implies --no-ignore-parent for source control ignore files as
        well.

        This flag can be disabled with --ignore-vcs.

    --no-require-git
        When this flag is given, source control ignore files such as .gitignore
        are respected even if no git repository is present.

        By default, ripgrep will only respect filter rules from source control
        ignore files when ripgrep detects that the search is executed inside a
        source control repository. For example, when a .git directory is
        observed.

        This flag relaxes the default restriction. For example, it might be
        useful when the contents of a git repository are stored or copied
        somewhere, but where the repository state is absent.

        This flag can be disabled with --require-git.

    --one-file-system
        When enabled, ripgrep will not cross file system boundaries relative to
        where the search started from.

        Note that this applies to each path argument given to ripgrep. For
        example, in the command

            rg --one-file-system /foo/bar /quux/baz

        ripgrep will search both /foo/bar and /quux/baz even if they are on
        different file systems, but will not cross a file system boundary when
        traversing each path's directory tree.

        This is similar to find's -xdev or -mount flag.

        This flag can be disabled with --no-one-file-system.

    -t TYPE, --type=TYPE
        This flag limits ripgrep to searching files matching TYPE. Multiple
        -t/--type flags may be provided.

        This flag supports the special value all, which will behave as if
        -t/--type was provided for every file type supported by ripgrep
        (including any custom file types). The end result is that --type=all
        causes ripgrep to search in "whitelist" mode, where it will only search
        files it recognizes via its type definitions.

        Note that this flag has lower precedence than both the -g/--glob flag
        and any rules found in ignore files.

        To see the list of available file types, use the --type-list flag.

    -T TYPE, --type-not=TYPE
        Do not search files matching TYPE. Multiple -T/--type-not flags may be
        provided. Use the --type-list flag to list all available types.

        This flag supports the special value all, which will behave as if
        -T/--type-not was provided for every file type supported by ripgrep
        (including any custom file types). The end result is that
        --type-not=all causes ripgrep to search in "blacklist" mode, where it
        will only search files that are unrecognized by its type definitions.

        To see the list of available file types, use the --type-list flag.

    --type-add=TYPESPEC
        This flag adds a new glob for a particular file type. Only one glob can
        be added at a time. Multiple --type-add flags can be provided. Unless
        --type-clear is used, globs are added to any existing globs defined
        inside of ripgrep.

        Note that this must be passed to every invocation of ripgrep. Type
        settings are not persisted. See CONFIGURATION FILES for a workaround.

        Example:

            rg --type-add 'foo:*.foo' -tfoo PATTERN

        This flag can also be used to include rules from other types with the
        special include directive. The include directive permits specifying one
        or more other type names (separated by a comma) that have been defined
        and its rules will automatically be imported into the type specified.
        For example, to create a type called src that matches C++, Python and
        Markdown files, one can use:

            --type-add 'src:include:cpp,py,md'

        Additional glob rules can still be added to the src type by using this
        flag again:

            --type-add 'src:include:cpp,py,md' --type-add 'src:*.foo'

        Note that type names must consist only of Unicode letters or numbers.
        Punctuation characters are not allowed.

    --type-clear=TYPE
        Clear the file type globs previously defined for TYPE. This clears any
        previously defined globs for the TYPE, but globs can be added after
        this flag.

        Note that this must be passed to every invocation of ripgrep. Type
        settings are not persisted. See CONFIGURATION FILES for a workaround.

    -u, --unrestricted
        This flag reduces the level of "smart" filtering. Repeated uses (up to
        3) reduces the filtering even more. When repeated three times, ripgrep
        will search every file in a directory tree.

        A single -u/--unrestricted flag is equivalent to --no-ignore. Two
        -u/--unrestricted flags is equivalent to --no-ignore -./--hidden. Three
        -u/--unrestricted flags is equivalent to --no-ignore -./--hidden
        --binary.

        The only filtering ripgrep still does when -uuu is given is to skip
        symbolic links and to avoid printing matches from binary files.
        Symbolic links can be followed via the -L/--follow flag, and binary
        files can be treated as text files via the -a/--text flag.

OUTPUT OPTIONS:
    -A NUM, --after-context=NUM
        Show NUM lines after each match.

        This overrides the --passthru flag and partially overrides the
        -C/--context flag.

    -B NUM, --before-context=NUM
        Show NUM lines before each match.

        This overrides the --passthru flag and partially overrides the
        -C/--context flag.

    --block-buffered
        When enabled, ripgrep will use block buffering. That is, whenever a
        matching line is found, it will be written to an in-memory buffer and
        will not be written to stdout until the buffer reaches a certain size.
        This is the default when ripgrep's stdout is redirected to a pipeline
        or a file. When ripgrep's stdout is connected to a tty, line buffering
        will be used by default. Forcing block buffering can be useful when
        dumping a large amount of contents to a tty.

        This overrides the --line-buffered flag.

        This flag can be disabled with --no-block-buffered.

    -b, --byte-offset
        Print the 0-based byte offset within the input file before each line of
        output. If -o/--only-matching is specified, print the offset of the
        matched text itself.

        If ripgrep does transcoding, then the byte offset is in terms of the
        result of transcoding and not the original data. This applies similarly
        to other transformations on the data, such as decompression or a --pre
        filter.

        This flag can be disabled with --no-byte-offset.

    --color=WHEN
        This flag controls when to use colors. The default setting is auto,
        which means ripgrep will try to guess when to use colors. For example,
        if ripgrep is printing to a tty, then it will use colors, but if it is
        redirected to a file or a pipe, then it will suppress color output.

        ripgrep will suppress color output by default in some other
        circumstances as well. These include, but are not limited to:

        • When the TERM environment variable is not set or set to dumb.

        • When the NO_COLOR environment variable is set (regardless of value).

        • When flags that imply no use for colors are given. For example,
        --vimgrep and --json.

        The possible values for this flag are:

        never: Colors will never be used.

        auto: The default. ripgrep tries to be smart.

        always: Colors will always be used regardless of where output is sent.

        ansi: Like 'always', but emits ANSI escapes (even in a Windows
        console).

        This flag also controls whether hyperlinks are emitted. For example,
        when a hyperlink format is specified, hyperlinks won't be used when
        color is suppressed. If one wants to emit hyperlinks but no colors,
        then one must use the --colors flag to manually set all color styles to
        none:

            --colors 'path:none' \
            --colors 'line:none' \
            --colors 'column:none' \
            --colors 'match:none'

    --colors=COLOR_SPEC
        This flag specifies color settings for use in the output. This flag may
        be provided multiple times. Settings are applied iteratively.
        Pre-existing color labels are limited to one of eight choices: red,
        blue, green, cyan, magenta, yellow, white and black. Styles are limited
        to nobold, bold, nointense, intense, nounderline or underline.

        The format of the flag is {type}:{attribute}:{value}. type should be
        one of path, line, column or match. attribute can be fg, bg or style.
        value is either a color (for fg and bg) or a text style. A special
        format, {type}:none, will clear all color settings for type.

        For example, the following command will change the match color to
        magenta and the background color for line numbers to yellow:

            rg --colors 'match:fg:magenta' --colors 'line:bg:yellow'

        Extended colors can be used for value when the tty supports ANSI color
        sequences. These are specified as either x (256-color) or x,x,x (24-bit
        truecolor) where x is a number between 0 and 255 inclusive. x may be
        given as a normal decimal number or a hexadecimal number, which is
        prefixed by 0x.

        For example, the following command will change the match background
        color to that represented by the rgb value (0,128,255):

            rg --colors 'match:bg:0,128,255'

        or, equivalently,

            rg --colors 'match:bg:0x0,0x80,0xFF'

        Note that the intense and nointense styles will have no effect when
        used alongside these extended color codes.

    --column
        Show column numbers (1-based). This only shows the column numbers for
        the first match on each line. This does not try to account for Unicode.
        One byte is equal to one column. This implies -n/--line-number.

        When -o/--only-matching is used, then the column numbers written
        correspond to the start of each match.

        This flag can be disabled with --no-column.

    -C NUM, --context=NUM
        Show NUM lines before and after each match. This is equivalent to
        providing both the -B/--before-context and -A/--after-context flags
        with the same value.

        This overrides the --passthru flag. The -A/--after-context and
        -B/--before-context flags both partially override this flag, regardless
        of the order. For example, -A2 -C1 is equivalent to -A2 -B1.

    --context-separator=SEPARATOR
        The string used to separate non-contiguous context lines in the output.
        This is only used when one of the context flags is used (that is,
        -A/--after-context, -B/--before-context or -C/--context). Escape
        sequences like \x7F or \t may be used. The default value is --.

        When the context separator is set to an empty string, then a line break
        is still inserted. To completely disable context separators, use the
        --no-context-separator flag.

    --field-context-separator=SEPARATOR
        Set the field context separator. This separator is only used when
        printing contextual lines. It is used to delimit file paths, line
        numbers, columns and the contextual line itself. The separator may be
        any number of bytes, including zero. Escape sequences like \x7F or \t
        may be used.

        The - character is the default value.

    --field-match-separator=SEPARATOR
        Set the field match separator. This separator is only used when
        printing matching lines. It is used to delimit file paths, line
        numbers, columns and the matching line itself. The separator may be any
        number of bytes, including zero. Escape sequences like \x7F or \t may
        be used.

        The : character is the default value.

    --heading
        This flag prints the file path above clusters of matches from each file
        instead of printing the file path as a prefix for each matched line.

        This is the default mode when printing to a tty.

        When stdout is not a tty, then ripgrep will default to the standard
        grep-like format. One can force this format in Unix-like environments
        by piping the output of ripgrep to cat. For example, rg foo | cat.

        This flag can be disabled with --no-heading.

    -h, --help
        This flag prints the help output for ripgrep.

        Unlike most other flags, the behavior of the short flag, -h, and the
        long flag, --help, is different. The short flag will show a condensed
        help output while the long flag will show a verbose help output. The
        verbose help output has complete documentation, where as the condensed
        help output will show only a single line for every flag.

    --hostname-bin=COMMAND
        This flag controls how ripgrep determines this system's hostname. The
        flag's value should correspond to an executable (either a path or
        something that can be found via your system's PATH environment
        variable). When set, ripgrep will run this executable, with no
        arguments, and treat its output (with leading and trailing whitespace
        stripped) as your system's hostname.

        When not set (the default, or the empty string), ripgrep will try to
        automatically detect your system's hostname. On Unix, this corresponds
        to calling gethostname. On Windows, this corresponds to calling
        GetComputerNameExW to fetch the system's "physical DNS hostname."

        ripgrep uses your system's hostname for producing hyperlinks.

    --hyperlink-format=FORMAT
        Set the format of hyperlinks to use when printing results. Hyperlinks
        make certain elements of ripgrep's output, such as file paths,
        clickable. This generally only works in terminal emulators that support
        OSC-8 hyperlinks. For example, the format file://{host}{path} will emit
        an RFC 8089 hyperlink. To see the format that ripgrep is using, pass
        the --debug flag.

        Alternatively, a format string may correspond to one of the following
        aliases: default, none, file, grep+, kitty, macvim, textmate, vscode,
        vscode-insiders, vscodium. The alias will be replaced with a format
        string that is intended to work for the corresponding application.

        The following variables are available in the format string:

        {path}: Required. This is replaced with a path to a matching file. The
        path is guaranteed to be absolute and percent encoded such that it is
        valid to put into a URI. Note that a path is guaranteed to start with a
        /.

        {host}: Optional. This is replaced with your system's hostname. On
        Unix, this corresponds to calling gethostname. On Windows, this
        corresponds to calling GetComputerNameExW to fetch the system's
        "physical DNS hostname." Alternatively, if --hostname-bin was provided,
        then the hostname returned from the output of that program will be
        returned. If no hostname could be found, then this variable is replaced
        with the empty string.

        {line}: Optional. If appropriate, this is replaced with the line number
        of a match. If no line number is available (for example, if
        --no-line-number was given), then it is automatically replaced with the
        value 1.

        {column}: Optional, but requires the presence of {line}. If
        appropriate, this is replaced with the column number of a match. If no
        column number is available (for example, if --no-column was given),
        then it is automatically replaced with the value 1.

        {wslprefix}: Optional. This is a special value that is set to
        wsl$/WSL_DISTRO_NAME, where WSL_DISTRO_NAME corresponds to the value of
        the equivalent environment variable. If the system is not Unix or if
        the WSL_DISTRO_NAME environment variable is not set, then this is
        replaced with the empty string.

        A format string may be empty. An empty format string is equivalent to
        the none alias. In this case, hyperlinks will be disabled.

        At present, ripgrep does not enable hyperlinks by default. Users must
        opt into them. If you aren't sure what format to use, try default.

        Like colors, when ripgrep detects that stdout is not connected to a
        tty, then hyperlinks are automatically disabled, regardless of the
        value of this flag. Users can pass --color=always to forcefully emit
        hyperlinks.

        Note that hyperlinks are only written when a path is also in the output
        and colors are enabled. To write hyperlinks without colors, you'll need
        to configure ripgrep to not colorize anything without actually
        disabling all ANSI escape codes completely:

            --colors 'path:none' \
            --colors 'line:none' \
            --colors 'column:none' \
            --colors 'match:none'

        ripgrep works this way because it treats the --color flag as a proxy
        for whether ANSI escape codes should be used at all. This means that
        environment variables like NO_COLOR=1 and TERM=dumb not only disable
        colors, but hyperlinks as well. Similarly, colors and hyperlinks are
        disabled when ripgrep is not writing to a tty. (Unless one forces the
        issue by setting --color=always.)

        If you're searching a file directly, for example:

            rg foo path/to/file

        then hyperlinks will not be emitted since the path given does not
        appear in the output. To make the path appear, and thus also a
        hyperlink, use the -H/--with-filename flag.

        For more information on hyperlinks in terminal emulators, see:
        https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

    --include-zero
        When used with -c/--count or --count-matches, this causes ripgrep to
        print the number of matches for each file even if there were zero
        matches. This is disabled by default but can be enabled to make ripgrep
        behave more like grep.

        This flag can be disabled with --no-include-zero.

    --line-buffered
        When enabled, ripgrep will always use line buffering. That is, whenever
        a matching line is found, it will be flushed to stdout immediately.
        This is the default when ripgrep's stdout is connected to a tty, but
        otherwise, ripgrep will use block buffering, which is typically faster.
        This flag forces ripgrep to use line buffering even if it would
        otherwise use block buffering. This is typically useful in shell
        pipelines, for example:

            tail -f something.log | rg foo --line-buffered | rg bar

        This overrides the --block-buffered flag.

        This flag can be disabled with --no-line-buffered.

    -n, --line-number
        Show line numbers (1-based).

        This is enabled by default when stdout is connected to a tty.

        This flag can be disabled by -N/--no-line-number.

    -N, --no-line-number
        Suppress line numbers.

        Line numbers are off by default when stdout is not connected to a tty.

        Line numbers can be forcefully turned on by -n/--line-number.

    -M NUM, --max-columns=NUM
        When given, ripgrep will omit lines longer than this limit in bytes.
        Instead of printing long lines, only the number of matches in that line
        is printed.

        When this flag is omitted or is set to 0, then it has no effect.

    --max-columns-preview
        Prints a preview for lines exceeding the configured max column limit.

        When the -M/--max-columns flag is used, ripgrep will by default
        completely replace any line that is too long with a message indicating
        that a matching line was removed. When this flag is combined with
        -M/--max-columns, a preview of the line (corresponding to the limit
        size) is shown instead, where the part of the line exceeding the limit
        is not shown.

        If the -M/--max-columns flag is not set, then this has no effect.

        This flag can be disabled with --no-max-columns-preview.

    -0, --null
        Whenever a file path is printed, follow it with a NUL byte. This
        includes printing file paths before matches, and when printing a list
        of matching files such as with -c/--count, -l/--files-with-matches and
        --files. This option is useful for use with xargs.

    -o, --only-matching
        Print only the matched (non-empty) parts of a matching line, with each
        such part on a separate output line.

    --path-separator=SEPARATOR
        Set the path separator to use when printing file paths. This defaults
        to your platform's path separator, which is / on Unix and \ on Windows.
        This flag is intended for overriding the default when the environment
        demands it (e.g., cygwin). A path separator is limited to a single
        byte.

        Setting this flag to an empty string reverts it to its default
        behavior. That is, the path separator is automatically chosen based on
        the environment.

    --passthru
        Print both matching and non-matching lines.

        Another way to achieve a similar effect is by modifying your pattern to
        match the empty string. For example, if you are searching using rg foo,
        then using rg '^|foo' instead will emit every line in every file
        searched, but only occurrences of foo will be highlighted. This flag
        enables the same behavior without needing to modify the pattern.

        An alternative spelling for this flag is --passthrough.

        This overrides the -C/--context, -A/--after-context and
        -B/--before-context flags.

    -p, --pretty
        This is a convenience alias for --color=always --heading --line-number.
        This flag is useful when you still want pretty output even if you're
        piping ripgrep to another program or file. For example: rg -p foo |
        less -R.

    -q, --quiet
        Do not print anything to stdout. If a match is found in a file, then
        ripgrep will stop searching. This is useful when ripgrep is used only
        for its exit code (which will be an error code if no matches are
        found).

        When --files is used, ripgrep will stop finding files after finding the
        first file that does not match any ignore rules.

    -r REPLACEMENT, --replace=REPLACEMENT
        Replaces every match with the text given when printing results. Neither
        this flag nor any other ripgrep flag will modify your files.

        Capture group indices (e.g., $5) and names (e.g., $foo) are supported
        in the replacement string. Capture group indices are numbered based on
        the position of the opening parenthesis of the group, where the
        leftmost such group is $1. The special $0 group corresponds to the
        entire match.

        The name of a group is formed by taking the longest string of letters,
        numbers and underscores (i.e. [_0-9A-Za-z]) after the $. For example,
        $1a will be replaced with the group named 1a, not the group at index 1.
        If the group's name contains characters that aren't letters, numbers or
        underscores, or you want to immediately follow the group with another
        string, the name should be put inside braces. For example, ${1}a will
        take the content of the group at index 1 and append a to the end of it.

        If an index or name does not refer to a valid capture group, it will be
        replaced with an empty string.

        In shells such as Bash and zsh, you should wrap the pattern in single
        quotes instead of double quotes. Otherwise, capture group indices will
        be replaced by expanded shell variables which will most likely be
        empty.

        To write a literal $, use $$.

        Note that the replacement by default replaces each match, and not the
        entire line. To replace the entire line, you should match the entire
        line.

        This flag can be used with the -o/--only-matching flag.

    --sort=SORTBY
        This flag enables sorting of results in ascending order. The possible
        values for this flag are:

        none: (Default) Do not sort results. Fastest. Can be multi-threaded.

        path: Sort by file path. Always single-threaded. The order is
        determined by sorting files in each directory entry during traversal.
        This means that given the files a/b and a+, the latter will sort after
        the former even though + would normally sort before /.

        modified: Sort by the last modified time on a file. Always
        single-threaded.

        accessed: Sort by the last accessed time on a file. Always
        single-threaded.

        created: Sort by the creation time on a file. Always single-threaded.

        If the chosen (manually or by-default) sorting criteria isn't available
        on your system (for example, creation time is not available on ext4
        file systems), then ripgrep will attempt to detect this, print an error
        and exit without searching.

        To sort results in reverse or descending order, use the --sortr flag.
        Also, this flag overrides --sortr.

        Note that sorting results currently always forces ripgrep to abandon
        parallelism and run in a single thread.

    --sortr=SORTBY
        This flag enables sorting of results in descending order. The possible
        values for this flag are:

        none: (Default) Do not sort results. Fastest. Can be multi-threaded.

        path: Sort by file path. Always single-threaded. The order is
        determined by sorting files in each directory entry during traversal.
        This means that given the files a/b and a+, the latter will sort before
        the former even though + would normally sort after / when doing a
        reverse lexicographic sort.

        modified: Sort by the last modified time on a file. Always
        single-threaded.

        accessed: Sort by the last accessed time on a file. Always
        single-threaded.

        created: Sort by the creation time on a file. Always single-threaded.

        If the chosen (manually or by-default) sorting criteria isn't available
        on your system (for example, creation time is not available on ext4
        file systems), then ripgrep will attempt to detect this, print an error
        and exit without searching.

        To sort results in ascending order, use the --sort flag. Also, this
        flag overrides --sort.

        Note that sorting results currently always forces ripgrep to abandon
        parallelism and run in a single thread.

    --trim
        When set, all ASCII whitespace at the beginning of each line printed
        will be removed.

        This flag can be disabled with --no-trim.

    --vimgrep
        This flag instructs ripgrep to print results with every match on its
        own line, including line numbers and column numbers.

        With this option, a line with more than one match will be printed in
        its entirety more than once. For that reason, the total amount of
        output as a result of this flag can be quadratic in the size of the
        input. For example, if the pattern matches every byte in an input file,
        then each line will be repeated for every byte matched. For this
        reason, users should only use this flag when there is no other choice.
        Editor integrations should prefer some other way of reading results
        from ripgrep, such as via the --json flag. One alternative to avoiding
        exorbitant memory usage is to force ripgrep into single threaded mode
        with the -j/--threads flag. Note though that this will not impact the
        total size of the output, just the heap memory that ripgrep will use.

    -H, --with-filename
        This flag instructs ripgrep to print the file path for each matching
        line. This is the default when more than one file is searched. If
        --heading is enabled (the default when printing to a tty), the file
        path will be shown above clusters of matches from each file; otherwise,
        the file name will be shown as a prefix for each matched line.

        This flag overrides -I/--no-filename.

    -I, --no-filename
        This flag instructs ripgrep to never print the file path with each
        matching line. This is the default when ripgrep is explicitly
        instructed to search one file or stdin.

        This flag overrides -H/--with-filename.

    --sort-files
        DEPRECATED. Use --sort=path instead.

        This flag instructs ripgrep to sort search results by file path
        lexicographically in ascending order. Note that this currently disables
        all parallelism and runs search in a single thread.

        This flag overrides --sort and --sortr.

        This flag can be disabled with --no-sort-files.

OUTPUT MODES:
    -c, --count
        This flag suppresses normal output and shows the number of lines that
        match the given patterns for each file searched. Each file containing a
        match has its path and count printed on each line. Note that unless
        -U/--multiline is enabled, this reports the number of lines that match
        and not the total number of matches. In multiline mode, -c/--count is
        equivalent to --count-matches.

        If only one file is given to ripgrep, then only the count is printed if
        there is a match. The -H/--with-filename flag can be used to force
        printing the file path in this case. If you need a count to be printed
        regardless of whether there is a match, then use --include-zero.

        This overrides the --count-matches flag. Note that when -c/--count is
        combined with -o/--only-matching, then ripgrep behaves as if
        --count-matches was given.

    --count-matches
        This flag suppresses normal output and shows the number of individual
        matches of the given patterns for each file searched. Each file
        containing matches has its path and match count printed on each line.
        Note that this reports the total number of individual matches and not
        the number of lines that match.

        If only one file is given to ripgrep, then only the count is printed if
        there is a match. The -H/--with-filename flag can be used to force
        printing the file path in this case.

        This overrides the -c/--count flag. Note that when -c/--count is
        combined with -o/--only-matching, then ripgrep behaves as if
        --count-matches was given.

    -l, --files-with-matches
        Print only the paths with at least one match and suppress match
        contents.

        This overrides --files-without-match.

    --files-without-match
        Print the paths that contain zero matches and suppress match contents.

        This overrides -l/--files-with-matches.

    --json
        Enable printing results in a JSON Lines format.

        When this flag is provided, ripgrep will emit a sequence of messages,
        each encoded as a JSON object, where there are five different message
        types:

        begin: A message that indicates a file is being searched and contains
        at least one match.

        end: A message the indicates a file is done being searched. This
        message also include summary statistics about the search for a
        particular file.

        match: A message that indicates a match was found. This includes the
        text and offsets of the match.

        context: A message that indicates a contextual line was found. This
        includes the text of the line, along with any match information if the
        search was inverted.

        summary: The final message emitted by ripgrep that contains summary
        statistics about the search across all files.

        Since file paths or the contents of files are not guaranteed to be
        valid UTF-8 and JSON itself must be representable by a Unicode
        encoding, ripgrep will emit all data elements as objects with one of
        two keys: text or bytes. text is a normal JSON string when the data is
        valid UTF-8 while bytes is the base64 encoded contents of the data.

        The JSON Lines format is only supported for showing search results. It
        cannot be used with other flags that emit other types of output, such
        as --files, -l/--files-with-matches, --files-without-match, -c/--count
        or --count-matches. ripgrep will report an error if any of the
        aforementioned flags are used in concert with --json.

        Other flags that control aspects of the standard output such as
        -o/--only-matching, --heading, -r/--replace, -M/--max-columns, etc.,
        have no effect when --json is set. However, enabling JSON output will
        always implicitly and unconditionally enable --stats.

        A more complete description of the JSON format used can be found here:
        https://docs.rs/grep-printer/*/grep_printer/struct.JSON.html.

        This flag can be disabled with --no-json.

LOGGING OPTIONS:
    --debug
        Show debug messages. Please use this when filing a bug report.

        The --debug flag is generally useful for figuring out why ripgrep
        skipped searching a particular file. The debug messages should mention
        all files skipped and why they were skipped.

        To get even more debug output, use the --trace flag, which implies
        --debug along with additional trace data.

    --no-ignore-messages
        When this flag is enabled, all error messages related to parsing ignore
        files are suppressed. By default, error messages are printed to stderr.
        In cases where these errors are expected, this flag can be used to
        avoid seeing the noise produced by the messages.

        This flag can be disabled with --ignore-messages.

    --no-messages
        This flag suppresses some error messages. Specifically, messages
        related to the failed opening and reading of files. Error messages
        related to the syntax of the pattern are still shown.

        This flag can be disabled with --messages.

    --stats
        When enabled, ripgrep will print aggregate statistics about the search.
        When this flag is present, ripgrep will print at least the following
        stats to stdout at the end of the search: number of matched lines,
        number of files with matches, number of files searched, and the time
        taken for the entire search to complete.

        This set of aggregate statistics may expand over time.

        This flag is always and implicitly enabled when --json is used.

        Note that this flag has no effect if --files, -l/--files-with-matches
        or --files-without-match is passed.

        This flag can be disabled with --no-stats.

    --trace
        Show trace messages. This shows even more detail than the --debug flag.
        Generally, one should only use this if --debug doesn't emit the
        information you're looking for.

OTHER BEHAVIORS:
    --files
        Print each file that would be searched without actually performing the
        search. This is useful to determine whether a particular file is being
        searched or not.

        This overrides --type-list.

    --generate=KIND
        This flag instructs ripgrep to generate some special kind of output
        identified by KIND and then quit without searching. KIND can be one of
        the following values:

        man: Generates a manual page for ripgrep in the roff format.

        complete-bash: Generates a completion script for the bash shell.

        complete-zsh: Generates a completion script for the zsh shell.

        complete-fish: Generates a completion script for the fish shell.

        complete-powershell: Generates a completion script for PowerShell.

        The output is written to stdout. The list above may expand over time.

    --no-config
        When set, ripgrep will never read configuration files. When this flag
        is present, ripgrep will not respect the RIPGREP_CONFIG_PATH
        environment variable.

        If ripgrep ever grows a feature to automatically read configuration
        files in pre-defined locations, then this flag will also disable that
        behavior as well.

    --pcre2-version
        When this flag is present, ripgrep will print the version of PCRE2 in
        use, along with other information, and then exit. If PCRE2 is not
        available, then ripgrep will print an error message and exit with an
        error code.

    --type-list
        Show all supported file types and their corresponding globs. This takes
        any --type-add and --type-clear flags given into account. Each type is
        printed on its own line, followed by a : and then a comma-delimited
        list of globs for that type on the same line.

    -V, --version
        This flag prints ripgrep's version. This also may print other relevant
        information, such as the presence of target specific optimizations and
        the git revision that this build of ripgrep was compiled from.
** 最基础的
rg 'test'  a.txt
** -w有word之意，表示搜索的字符串作为一个独立的单词时才会被匹配到。
rg -w 'test'  a.txt
** 使用-i选项，即可在搜索时不区分大小写
rg -i 'test' a.txt
** -l只打印有匹配的文件名
rg -l 'test'  a.txt
** -C 输出匹配上下几行的内容
rg -C 2 'c'  a.txt
** 使用 -e REGEX 来指定正则表达式
rg -e "*sql" -C 2
*** 默认 rg 会忽略 .gitignore 和隐藏文件，可以使用 -uu 来查询所有内容
rg -uu "word" .
*** 可以使用 -t type 来指定文件类型：
rg -t markdown "mysql" .  # 在 md 文件中查找 “mysql” 关键字
支持的文件类型可以通过 rg --type-list 查看
*** 搜索文件
列出当前文件夹会进行查询的所有文件且搜索以 md 为后缀的文件
rg --files . | rg -e ".md$" # 正则匹配
* 查看当前shell
echo $SHELL
* sudo !!
#+begin_example
将最后一次使用的命令加sudo后运行
#+end_example
* 7z
主页：http://www.7-zip.org/
中文主页：http://7z.sparanoid.com/
命令行版本下载：http://7z.sparanoid.com/download.html

Windows去官网下载安装包安装
linux使用命令安装：sudo apt install p7zip-full
                sudo pacman -S p7zip
注:
p7zip、p7zip-full和p7zip-rar三个版本的区别：
p7zip和p7zip-full之间的区别在于p7zip是较轻的版本，仅支持.7z，而完整版本支持更多7z压缩算法（用于音频文件等）。
p7zip-rar软件包提供对7z的RAR文件的支持，在大多数情况下，安装p7zip-full应该足够了。

7z命令行的使用格式： 7z <command> [<switch>...] <base_archive_name> [<arguments>...]
这里有两个参数是必须的，command 和base_archive_name,对应操作和生成的压缩文件(或解压文件)的路径

** 主要特征：

 - 全新的LZMA算法加大了7z格式的压缩比
 - 支持格式：
  - 压缩 / 解压缩：7z, XZ, BZIP2, GZIP, TAR, ZIP
  - 仅解压缩：ARJ, CAB, CHM, CPIO, DEB, DMG, FAT, HFS, ISO, LZH, LZMA, MBR, MSI, NSIS, NTFS, RAR, RPM, UDF, VHD, WIM, XAR, Z

** 退出代码

0 ： 正常，没有错误；

1 ： 警告，没有致命的错误，例如某些文件正在被使用，没有被压缩；

2 ： 致命错误；

7 ： 命令行错误；

8 ： 没有足够的内存；

255 ： 用户停止了操作；

** 使用语法

7z <命令行> [<选项>...] <基本档案名称> [<参数变量>...]

在方括号内的表达式(“[” 和 “]”之间的字符)是可选的。

在书名号内的表达式(“<” 和 “>”之间的字符)是必须替换的表达式(而且要去掉括号)。

7-Zip 支持和 Windows 相类似的通配符：

“*”可以使用星号代替零个或多个字符。

“?”可以用问号代替名称中的单个字符。

如果只用*，7-Zip 会将其视为任何扩展名的全部文件。

** 命令及实例

*** a 添加文件到压缩档案。

7z a archive1.zip subdir\ ：增加subdir文件夹下的所有的文件和子文件夹到archive1.zip中，archived1.zip中的文件名包含subdir\前缀。

7z a archive2.zip .\subdir\* ：增加subdir文件夹下的所有的文件和子文件夹到archive1.zip中，archived2.zip中的文件名不包含subdir\前缀。

cd /D c:\dir1\

7z a c:\archive3.zip dir2\dir3\ ：archiive3.zip中的文件名将包含dir2\dir3\前缀，但是不包含c:\dir1前缀。

7z a Files.7z *.txt -r ： 增加当前文件夹及其子文件夹下的所有的txt文件到Files.7z中。

*** b 测试 CPU 运行速度及检查内存错误。

*** d 从压缩档案删除文件。

7z d archive.zip *.bak -r ：从archive.zip中删除所有的bak文件。

*** e 从压缩档案中释放文件到当前目录中。或者到指定的输出文件夹。输出文件夹设置可以通过 -o (设置输出文件夹) 选项来更改。此命令会将所有被释放的文件放置到一个文件夹。如果您想使用完整路径释放文件，您必须使用 x (完整路径释放) 命令。

7z e archive.zip ：从压缩档案 archive.zip 中释放所有文件到当前文件夹。

7z e archive.zip -oc:\soft *.cpp ：从压缩档案 archive.zip 中释放 *.cpp 文件到 c:\soft 文件夹。

*** l 列出压缩档案内容。

7z l archive.zip ：列出压缩档案 archive.zip 的内容。

*** t 测试压缩档案文件的完整性。

7z t archive.zip *.doc ：在压缩档案 archive.zip 中测试 *.doc 文件的完整性。

*** u 在压缩档案文件中使用较新的文件替换掉较旧的文件。

7z u archive.zip *.doc ：在压缩档案 archive.zip 中更新 *.doc 文件。

*** x 在当前目录中，使用完整路径从压缩档案中释放文件.或者到指定的输出文件夹。

7z x archive.zip ：从压缩档案 archive.zip 中释放所有文件到当前文件夹。

7z x archive.zip -oc:\soft *.cpp ：从压缩档案 archive.zip 中释放 *.cpp 文件到 c:\soft 文件夹。

** 更多的选项

*** -- 在命令行中使“--”后的选项开关“-”都失效。这样就允许在命令行中使用文件名以“-”开头的文件。

7z t -- -ArchiveName.7z ：测试 -ArchiveName.7z 压缩档案.

*** -i指定压缩时附加文件或一类文件。此选项可附件添加多个类型。

i[<recurse_type>]<file_ref> 其中<recurse_type>为可以为r[- | 0]（具体的-r选项见后面-r），<file_ref>可以为@{listfile} | !{wildcard}。

7z a -tzip src.zip *.txt -ir!DIR1\*.cpp ：从当前目录中添加 *.txt 文件，和 DIR1 目录及其子目录中的 *.cpp 文件到 src.zip 压缩档案。

*** -x 指定某一文件或某一类文件从操作中排除。此选项可同时排除多个类型。

x[<recurse_type>]<file_ref> 其中<recurse_type>为可以为r[- | 0]（具体的-r选项见后面-r），<file_ref>可以为@{listfile} | !{wildcard}。

7z a -tzip archive.zip *.txt -x!temp.* ：添加除 temp.* 文件之外的所有 *.txt 文件到压缩档案 archive.zip。

*** -o 指定释放文件的输出文件夹。此选项只能和释放命令配合使用。

7z x archive.zip -oc:\Doc ：从 archive.zip 压缩档案释放所有文件到 c:\Doc 文件夹。

*** -r 递归子目录选项。

-r 开启递归子目录。对于 e (释放)、l (列表)、t (测试)、x (完整路径释放) 这些在压缩档案中操作的命令， 会默认使用此选项。

-r- 关闭递归子目录。对于 a (添加)、d (删除)、u (更新) 等所有需扫描磁盘文件的命令，会默认使用此选项。

-r0 开启递归子目录。但只应用于通配符。

7z l archive.zip -r- *.doc ：列出在 archive.zip 压缩档案中根目录下的 *.doc 文件。

7z a -tzip archive.zip -r src\*.cpp src\*.h ：将 src 目录及其子目录中的 *.cpp 及 *.h 文件添加到 archive.zip 压缩档案。

*** -t 指定压缩档案格式。指定压缩档案格式。它们可以是：zip、7z、rar、cab、gzip、bzip2、tar 或其它格式。而 默认值是 7z 格式。

7z a -tzip archive.zip *.txt ：使用 zip 格式从当前目录中添加所有 *.txt 文件到压缩档案 archive.zip。

*** -y 使 7-Zip 执行命令时的大多数提示失效。您可以使用此选项来阻止在 e (释放) 和 x (完整路径释放) 命令中文件覆盖时的提示。

7z x src.zip -y ：从 src.zip 释放所有文件。所有的覆盖提示将被阻止且所有相同文件名的文件将被覆盖。

*** -v指定分卷大小。

{Size}[b | k | m | g]

指定分卷大小，可以使用字节、KB(1 KB＝1024 字节)，MB(1 MB = 1024 KB)或 GB(1 GB = 1024 MB)。如果您只指定了 {Size}，7-zip 将把它视为字。

7z a a.7z *.txt -v10k -v15k -v2m ： 创建 a.7z 分卷压缩档案。第一个分卷为 10 KB，第二个为 15 KB，剩下全部为 2 MB。

*** -p 指定密码。

7z x archive.zip -psecret ：将设有密码“secret”的压缩档案 archive.zip 中所有文件释放。

*** -ao 指定在释放期间如何覆盖硬盘上现有的同名文件。

语法：-ao[a | s | u ]

-aoa 直接覆盖现有文件，而没有任何提示。

-aos 跳过现有文件，其不会被覆盖。

-aou 如果相同文件名的文件以存在，将自动重命名被释放的文件。举个例子，文件 file.txt 将被自动重命名为 file_1.txt。

-aot 如果相同文件名的文件以存在，将自动重命名现有的文件。举个例子，文件 file.txt 将被自动重命名为 file_1.txt。

7z x test.zip -aoa ：从压缩档案 test.zip 中释放所有文件并却不做提示直接覆盖现有文件。

*** -an 不解析命令行中的 archive_name 区域。此选项必须和 -i (附加文件) 开关一起使用。比如您为压缩档案使用列表文件，您就需要指定 -ai 选项，所以您需要禁止解析命令行中的 archive_name 区域。

实例见后面的-ai和-ax中。

*** -ai 指定附加文件，包括压缩档案文件名及通配符。此选项可同时附加多个类型。

ai[<recurse_type>]<file_ref> 其中<recurse_type>为可以为r[- | 0]（具体的-r选项见后面-r），<file_ref>可以为@{listfile} | !{wildcard}。

7z t -an -air!*.7z ： 在当前目录及子目录下测试 *.7z 压缩档案。

*** -ax 指定必须从操作中排除的压缩档案。此选项可同时排除多个类型。

ax[<recurse_type>]<file_ref> 其中<recurse_type>为可以为r[- | 0]（具体的-r选项见后面-r），<file_ref>可以为@{listfile} | !{wildcard}。

7z t -an -ai!*.7z -ax!a*.7z ：测试除 a*.7z 之外的 *.7z 压缩档案。

** 更多的不常用的选项，可以查看帮助。

例如：-m设置压缩算法；

-scs 设置要压缩的文件的列表文件的字符集；

-seml通过电子邮件发送压缩档；

-sfx创建自释放档；

-si从标准输入读入数据，

-so从输出到标准输 出；

-slp设置大内存模式；

-slt显示技术信息；

-ssc设置区分大小写；

-ssw压缩正在写入的文件；

-u更新选项。

 a test.zip ./test/* -mx0

功能：把test文件夹中所有文件以存储压缩的模式压缩成zip格式的文件，压缩文件为test.zip

参数说明：

a为添加选项

-tZip为压缩格式（-t7z...）

压缩率具体参数如下：

-mx0 仅存储不压缩-----------------速度最快，无压缩，zip大小等同原始文件夹

-mx1 极速压缩

-mx3 快速压缩

-mx5 标准压缩

-mx7 最大压缩

-mx9 极限压缩

必选参数：最常用的命令有a（压缩）、x（解压），其它的命令诸如删除，解压出来不保留目录结构这种，一般情况下都用不到。

可选参数：最常用的就是-t{Type}

Type默认值为7z，还有其它的如：

Type        Format        Example filename

-t7z        7Z        archive.7z(默认)

-tgzip        GZIP        archive.gzip，archive.gz

-tzip        ZIP        archive.zip(兼容)

-tbzip2        BZIP2        archive.bzip2

-ttar        TAR        tarball.tar(Unix/Linux)

-tiso        ISO        image.iso(可能不支持)

-tudf        UDF        disk.udf

常用的就是-t{Type}以及-r、-o、-y

例如

7z.exe e -tgzip  *.gz

7z.exe e E:\Report\Process\Decote\*.zip -o E:\Report\Process\Decote\

解压命令：7z x -tzip -y xx-13.zip （解压到当前目录，如需改变输出目录，需要附加使用-o）

压缩命令：7z a -tzip -r xx.zip a\* b\*

将目录a、目录b，压缩成一个xx.zip

更多参数的详情，可以参考这里：http://www.dotnetperls.com/7-zip-examples

在Windows的64位操作系统下，除需要7z.exe外，还需要7z.dll，我将他们打包为一个zip文件，否则你执行命令的时候可能会遇到上面的错误。
* history
- 清除所有记录
  history -c
- 清除指定记录
  history -d 5 4 3
  删除第5 4 和3序号的记录
* progress
** help
progress - Coreutils Viewer
---------------------
Shows progress on file manipulations (cp, mv, dd, ...)

Monitored commands (default, you can add virtually anything):
cp mv dd tar bsdtar cat rsync scp grep fgrep egrep cut sort cksum md5sum sha1sum sha224sum sha256sum sha384sum sha512sum adb gzip gunzip bzip2 bunzip2 xz unxz lzma unlzma 7z 7za zip unzip zcat bzcat lzcat coreutils split gpg

Usage: progress [-qdwmM] [-W secs] [-c command] [-p pid]
  -q --quiet                   hides all messages
  -d --debug                   shows all warning/error messages
  -w --wait                    estimate I/O throughput and ETA (slower display)
  -W --wait-delay secs         wait 'secs' seconds for I/O estimation (implies -w, default=1.0)
  -m --monitor                 loop while monitored processes are still running
  -M --monitor-continuously    like monitor but never stop (similar to watch progress)
  -a --additional-command cmd  add additional command to default command list
  -c --command cmd             monitor only this command name (ex: firefox)
  -p --pid id                  monitor only this process ID (ex: `pidof firefox`)
  -i --ignore-file file        do not report process if using file
  -o --open-mode {r|w|u}       report only files opened for read, write, or read and write
  -v --version                 show program version and exit
  -h --help                    display this help and exit


Multiple options allowed for: -a -c -p -i. Use PROGRESS_ARGS for permanent arguments.
** 显示指定命令的执行进度
*** 单次显示
#+BEGIN_SRC sh
 progress -c ffmpeg
#+END_SRC
*** 持续显示
#+BEGIN_SRC sh
 progress -M -c ffmpeg
#+END_SRC
如果想监控其它命令，只需将 ffmpeg 换成想监控的命令即可。
也可以连续使用多个 -c 同时监控多个命令的执行进度。
** 显示指定PID的执行进度
*** 单次显示
#+BEGIN_SRC sh
 progress -p 进程号
 #+END_SRC
*** 持续显示
#+BEGIN_SRC sh
 progress -M -p 进程号
 #+END_SRC
** Progress 一些其它操作方式
#+BEGIN_SRC sh
 watch progress -wq
 watch progress -wc firefox
#+END_SRC
* kill
    #+BEGIN_SRC sh
      kill pid
      kill -9 pid      立即结束pid，不能被忽略或捕获
    #+END_SRC
* tldr
** 安装
#+begin_src sh
  paru -S tldr
#+end_src
** 用法
#+begin_src
    Display simple help pages for command-line tools from the tldr-pages project.
    Note: the `--language` and `--list` options are not required by the client specification, but most clients implement them.
    More information: https://github.com/tldr-pages/tldr/blob/main/CLIENT-SPECIFICATION.md#command-line-interface.

    - Print the tldr page for a specific command (hint: this is how you got here!):
      tldr command

    - Print the tldr page for a specific subcommand:
      tldr command subcommand

    - Print the tldr page for a command in the given [L]anguage (if available, otherwise fall back to English):
      tldr --language language_code command

    - Print the tldr page for a command from a specific [p]latform:
      tldr --platform android|common|freebsd|linux|osx|netbsd|openbsd|sunos|windows command

    - [u]pdate the local cache of tldr pages:
      tldr --update

    - [l]ist all pages for the current platform and `common`:
      tldr --list

    - [l]ist all available subcommand pages for a command:
      tldr --list | grep command | column
#+end_src
* 回收站-trash
** 安装
#+begin_src sh
  paru -S trash-cli
#+end_src
** 用法
#+begin_src sh
  tldr trash-cli
#+end_src
* date
** 使用 date 命令时，可以通过 + 选项指定显示格式。例如： date "+%Y-%m-%d %H:%M:%S"
输出示例： 2024-11-22 14:30:45
** 常用格式化代码：
|-----+------------------------|
| %Y: | 四位数的年份 (如 2024)    |
|-----+------------------------|
| %m: | 两位数的月份 (01-12)     |
|-----+------------------------|
| %d: | 两位数的日期 (01-31)     |
|-----+------------------------|
| %H: | 小时 (24小时制)          |
|-----+------------------------|
| %I: | 小时 (12小时制)          |
|-----+------------------------|
| %M: | 分钟                   |
|-----+------------------------|
| %S: | 秒                     |
|-----+------------------------|
| %p: | 显示 AM 或 PM           |
|-----+------------------------|
| %a: | 星期的缩写 (如 Mon)      |
|-----+------------------------|
| %A: | 星期的全称 (如 Monday)   |
|-----+------------------------|
| %b: | 月份的缩写 (如 Nov)      |
|-----+------------------------|
| %B: | 月份的全称 (如 November) |
|-----+------------------------|
** 完整的格式化代码可以通过 man date 查看。
* ln
#+begin_src
    1. 硬链接 (ln)
    格式：
    ln 原文件 目标文件
    特点：
        硬链接指向相同的 inode（即同一个文件数据块）。
        删除其中一个文件不会影响另一个，因为数据仍然存在，直到所有硬链接被删除。
        不能跨文件系统（不同磁盘或分区）创建硬链接。
        不能对目录创建硬链接（普通用户）。
    示例：

    ln file1.txt file2.txt
    ls -i file1.txt file2.txt  # 观察 inode 号是否相同

    2. 软链接（符号链接）（ln -s）

    格式：

    ln -s 原文件 目标文件

    特点：

        软链接类似于 Windows 快捷方式，存储的是原文件的路径，而不是数据本身。
        删除原文件后，软链接变成“悬空链接”（即指向无效的目标）。
        可以跨文件系统和分区创建。
        可以对目录创建软链接。

    示例：

    ln -s /home/user/original.txt link.txt
    ls -l link.txt  # 观察是否有 `-> original.txt`

    3. 其他常用选项：

        -f：如果目标文件已存在，强制删除后再创建新链接。
        -v：显示详细信息。
        -n：防止对符号链接创建新链接（用于防止误操作）。

    示例：

    ln -sf /new/path/original.txt link.txt  # 强制更新软链接
#+end_src
* journalctl
#+begin_src
    journalctl 是 Linux 系统中用于查看 systemd 日志的工具，
    它可以查询、过滤和管理 systemd 产生的日志信息。
    以下是常见的 journalctl 用法：
    1. 查看所有日志
    journalctl
    默认情况下，它会从日志的最早时间开始显示所有日志。
    2. 按时间筛选日志
        查看今天的日志
    journalctl --since today
    查看最近 1 小时的日志
    journalctl --since "1 hour ago"
    查看特定时间段的日志
        journalctl --since "2025-02-01 12:00:00" --until "2025-02-01 14:00:00"
    3. 按服务筛选日志
        查看 nginx 服务日志
    journalctl -u nginx
    查看 sshd 服务日志（并持续跟踪）
        journalctl -u sshd -f
    4. 按进程或用户筛选日志
        查看特定 PID（进程 ID）的日志
    journalctl _PID=1234
    查看特定用户（UID）产生的日志
        journalctl _UID=1000
    5. 持续实时查看日志（类似 tail -f）
    journalctl -f
    这将在日志更新时实时显示新日志。
    6. 过滤内核日志
        仅查看内核日志
    journalctl -k
    实时查看内核日志
        journalctl -kf
    7. 查看启动日志
        查看当前启动（本次开机）的日志
    journalctl -b
    查看上次启动的日志
    journalctl -b -1
    查看特定启动 ID 的日志
        journalctl -b -2
    8. 按关键字搜索日志
        模糊搜索日志
    journalctl | grep "error"
    直接使用 journalctl 内置搜索
        journalctl -g "error"
    9. 清理日志
        查看日志占用空间
    journalctl --disk-usage
    清理日志（保留最近 500MB 日志）
    journalctl --vacuum-size=500M
    清理日志（保留最近 7 天的日志）
        journalctl --vacuum-time=7d
    10. 指定日志格式
        JSON 格式
    journalctl -o json-pretty
    短格式
        journalctl -o short
#+end_src
* cp
#+begin_src
    避免手动确认但不覆盖已有文件 →  cp -rn -v
    避免手动确认并覆盖所有文件    →  cp -rf -v
    自动输入 y（覆盖所有文件）    →  yes | cp -ir -v
    自动输入 n（不覆盖已有文件） →  yes n | cp -ir -v
    只覆盖比目标文件新的文件       →  cp -ru -v
#+end_src
* bat
    #+begin_src sh
    是一个增强版的 cat，用来高亮和分页查看文件内容。
      运行以下命令检查是否安装：

      which bat

      如果没有输出，说明未安装。
      2. 安装 bat

      根据你的操作系统，选择以下安装方法：

          Debian/Ubuntu:

      sudo apt update
      sudo apt install bat

      注意：某些版本中 bat 被命名为 batcat，使用时需要输入 batcat。

      3. 验证安装

      安装完成后，运行以下命令确认：

      bat --version

      4. 配置路径（如果需要）

      如果安装的 bat 被命名为 batcat，可以创建一个别名方便使用：

      alias bat='batcat'

      将上述命令添加到你的 ~/.bashrc 或 ~/.zshrc 文件中以便永久生效：

      echo "alias bat='batcat'" >> ~/.bashrc
      source ~/.bashrc

    #+end_src
* fastfetch
#+begin_example
ln -sT /home/nerd/Downloads/deploy-debian/fastfetch /home/nerd/.config/fastfetch
#+end_example
* ctrl-z   fg
#+begin_src
    Ctrl-Z: This is used to suspend (pause) the currently running foreground process in the terminal.
    fg: This command is used to bring a suspended background job back to the foreground.
    可以堆栈形式 多层 fg 吗
    在终端中，fg 命令只能恢复最近一个被暂停或被送入后台的作业。如果你有多个后台作业，fg 只会恢复最顶部的作业。如果你想恢复其他作业，需要指定作业的 ID 或任务号。
    可以通过以下方式管理多个后台作业：
    查看作业列表：使用 jobs 命令来列出当前终端会话中的所有作业和它们的状态。

       jobs

       输出示例：

       [1]  + 12345 Stopped    your-command
       [2]  - 12346 Stopped    another-command

       恢复特定作业：通过 fg 后面加上作业编号来恢复指定的作业。例如，要恢复编号为 2 的作业：

           fg %2

           多个作业：如果你有多个后台作业，它们会按照作业编号堆叠。每次执行 fg 时，只会恢复最顶部的作业，但可以通过 jobs 命令来查看和选择你想恢复的作业。
#+end_src
* ASCII表
#+begin_src 
    ASCII（American Standard Code for Information Interchange，美国信息交换标准代码）是一种字符编码标准，包含 128 个字符（0-127），用于表示英文字母、数字、标点符号和控制字符。以下是完整的 ASCII 码表：
    控制字符（0-31）
    十进制	十六进制	字符	描述
    0	0x00	NUL	空字符（Null）
    1	0x01	SOH	标题开始（Start of Heading）
    2	0x02	STX	正文开始（Start of Text）
    3	0x03	ETX	正文结束（End of Text）
    4	0x04	EOT	传输结束（End of Transmission）
    5	0x05	ENQ	询问（Enquiry）
    6	0x06	ACK	确认（Acknowledge）
    7	0x07	BEL	响铃（Bell）
    8	0x08	BS	退格（Backspace）
    9	0x09	HT	水平制表（Horizontal Tab）
    10	0x0A	LF	换行（Line Feed）
    11	0x0B	VT	垂直制表（Vertical Tab）
    12	0x0C	FF	换页（Form Feed）
    13	0x0D	CR	回车（Carriage Return）
    14	0x0E	SO	移出（Shift Out）
    15	0x0F	SI	移入（Shift In）
    16	0x10	DLE	数据链路转义（Data Link Escape）
    17	0x11	DC1	设备控制1（Device Control 1）
    18	0x12	DC2	设备控制2（Device Control 2）
    19	0x13	DC3	设备控制3（Device Control 3）
    20	0x14	DC4	设备控制4（Device Control 4）
    21	0x15	NAK	否定确认（Negative Acknowledge）
    22	0x16	SYN	同步空闲（Synchronous Idle）
    23	0x17	ETB	传输块结束（End of Transmission Block）
    24	0x18	CAN	取消（Cancel）
    25	0x19	EM	介质结束（End of Medium）
    26	0x1A	SUB	替补（Substitute）
    27	0x1B	ESC	转义（Escape）
    28	0x1C	FS	文件分隔符（File Separator）
    29	0x1D	GS	组分隔符（Group Separator）
    30	0x1E	RS	记录分隔符（Record Separator）
    31	0x1F	US	单元分隔符（Unit Separator）
    可打印字符（32-126）
    十进制	十六进制	字符	描述
    32	0x20	(空格)	空格（Space）
    33	0x21	!	感叹号
    34	0x22	"	双引号
    35	0x23	#	井号
    36	0x24	$	美元符号
    37	0x25	%	百分号
    38	0x26	&	和号（Ampersand）
    39	0x27	'	单引号
    40	0x28	(	左括号
    41	0x29	)	右括号
    42	0x2A	*	星号
    43	0x2B	+	加号
    44	0x2C	,	逗号
    45	0x2D	-	减号
    46	0x2E	.	句号
    47	0x2F	/	斜杠
    48-57	0x30-0x39	0-9	数字
    58	0x3A	:	冒号
    59	0x3B	;	分号
    60	0x3C	<	小于号
    61	0x3D	=	等号
    62	0x3E	>	大于号
    63	0x3F	?	问号
    64	0x40	@	电子邮件符号
    65-90	0x41-0x5A	A-Z	大写字母
    91	0x5B	[	左方括号
    92	0x5C	\	反斜杠
    93	0x5D	]	右方括号
    94	0x5E	^	抑扬符号（Caret）
    95	0x5F	_	下划线
    96	0x60	`	反引号
    97-122	0x61-0x7A	a-z	小写字母
    123	0x7B	{	左大括号
    124	0x7C		
    125	0x7D	}	右大括号
    126	0x7E	~	波浪号
    删除字符（127）
    十进制	十六进制	字符	描述
    127	0x7F	DEL	删除（Delete）
    
    这个 ASCII 码表是基础字符编码的一部分，被广泛用于计算机系统中。如果需要扩展字符（128-255），则属于扩展 ASCII 码（如 ISO-8859 或 UTF-8 编码）。
#+end_src
* ncdu
#+begin_src 
ncdu 是一个终端下查看磁盘占用的工具，类似 du，但带交互界面，适合快速找“大文件/大目录”。

安装：

Arch： sudo pacman -S ncdu

启动扫描当前目录：
ncdu
扫描指定目录：
ncdu /home
扫描整个系统（通常需要 root）：
sudo ncdu /
常用操作：
按键	功能
↑ ↓	上下移动
Enter / →	进入目录
←	返回上级
d	删除文件/目录
n	按名称排序
s	按大小排序
r	刷新
g	显示百分比/图形
q	退出

典型用途：

查看哪个目录占空间：

sudo ncdu /

进入后：

找最大的目录
一层层进入
删除日志、缓存、旧文件

例如：

/var
 ├── log
 ├── cache
 └── tmp

经常能发现：

docker 镜像
journal 日志
编译输出目录
下载缓存

远程服务器很常用：

ssh server
sudo ncdu /

因为它比：

du -sh *

快很多、直观很多。

一些实用参数：

只看同一文件系统（避免扫挂载盘）：

ncdu -x /

导出扫描结果：

ncdu -o file.json /

读取之前结果：

ncdu -f file.json

大目录扫描优化：

sudo ncdu -x / 2>/dev/null

避免权限报错刷屏。
#+end_src
* cp/mv
   | cmd      | source | target | 序号 |
   |----------+--------+--------+------|
   | cp/mv    | file   | file   |    1 |
   | cp/mv    | file   | folder |    2 |
   | cp/mv    | folder | file   |    3 |
   | cp/mv -r | folder | folder |    4 |

** <1> 分别分2种情况：
*** cp a.txt b.txt
*** 含义：把 a.txt 的内容复制为一个新的文件 b.txt。
*** 如果 b.txt 已存在，则会被覆盖；不存在则创建。
*** mv a.txt b.txt
*** 含义：把 a.txt 重命名为 b.txt。
*** 如果 b.txt 已存在，则会被覆盖；不存在则重命名。
** <2> 分别分2种情况
*** cp file.txt dir/
*** cp file.txt dir
*** mv file.txt dir/
*** mv file.txt dir
*** 这四个命令在目标 dir 存在时，效果完全一样：把 file.txt 复制/移动到 dir 目录下
** <3> 是错误的格式用法
** <4> 分别分2种情况, 须加 -r 才正确
*** cp -r dir1 dir2
*** 如果 dir2 不存在：会将 dir1 复制为 dir2（相当于重命名复制）。
*** 如果 dir2 已存在：会将 dir1 复制为 dir2/dir1。
*** cp -r dir1/ dir2
*** 如果 dir2 不存在：会将 dir1 复制为 dir2（相当于重命名复制）。
*** 如果 dir2 已存在：会将 dir1 内容复制到 dir2里。
*** ✅ 推荐记忆方式：
*** 你想要的结果	                  建议命令
*** 复制整个目录到目标中	          cp -r dir1 dir2/
*** 只复制目录的内容，不包括目录自身  cp -r dir1/ dir2/
*** 复制并改名（复制为别的目录名）	  cp -r dir1 newname
=======

* sudo dd制作upan

使用 dd 命令制作 U 盘启动盘（或写入镜像）时，请务必小心，因为一旦指定了错误的设备，将会导致数据丢失。下面是详细步骤：
🔧 使用 dd 命令制作 U 盘启动盘
1. 插入 U 盘

插入 U 盘之后，使用如下命令查看设备名：

lsblk

假设你看到 U 盘的设备是 /dev/sdb，而不是像 /dev/sdb1（后者是分区，前者是整块设备）。
2. 卸载 U 盘的挂载点（如果已挂载）

sudo umount /dev/sdb*

3. 执行 dd 命令写入镜像

假设你的系统镜像文件是 ubuntu.iso，位于当前目录：

sudo dd if=ubuntu.iso of=/dev/sdb bs=4M status=progress conv=fsync

参数解释：

    if=ubuntu.iso：输入文件（ISO 镜像）

    of=/dev/sdb：输出设备（整个 U 盘）

    bs=4M：块大小，提高写入速度（可换成 1M 也可以）

    status=progress：显示写入进度

    conv=fsync：确保缓存写入磁盘，增加数据完整性

4. 同步数据并安全移除

sync

等几秒钟后再移除 U 盘。
⚠️ 注意事项

    绝不要写错设备路径，尤其不要写成你的硬盘（如 /dev/sda），否则会导致整个系统被覆盖。

    备份数据：操作前请确保 U 盘中的重要数据已备份。

    如果你不确定设备名，可以先拔掉 U 盘，再插入一次，用 lsblk 或 dmesg | tail 确认设备名变化。

如果你要写入的是 .img 文件，比如树莓派镜像 raspbian.img，命令格式一样。

如需帮助确认设备名或写一个脚本简化这类操作，也可以告诉我。

