* 搜索软件
#+begin_src c
 nix search nixpkgs firefox
#+end_src
 或者,在网页里搜索
#+begin_src c
 https://search.nixos.org/packages
#+end_src
* channel
#+begin_src c
  sudo nix-channel --list
  sudo nix-channel --add https://mirrors.ustc.edu.cn/nix-channels/nixos-unstable nixos
  sudo nix-channel --update
  sudo nix-channel --remove nixos
  sudo nix-channel --remove nixpkgs
#+end_src
* lf文件管理器使用
lf 常用快捷键，按“日常使用”来记就够了：
** 文件操作
| Enter | 打开文件 |
| y     | 复制    |
| d     | 删除    |
| r     | 重命名   |
| p     | 粘贴    |

注意：lf 默认的复制/粘贴是“内部剪贴板”，不是系统剪贴板。
** 选择
| Space | 选择/取消当前文件 |
| v     | 反选           |
| uv    | 取消所有选择     |
** 搜索 / 跳转
| /  | 搜索文件名       |
| n  | 下一个匹配       |
| N  | 上一个匹配       |
| f  | 快速查找        |
| zh | 显示/隐藏隐藏文件 |

不同版本/配置里隐藏文件常见的是 zh，而不是我上一条说的 .。如果你的 lf 是默认配置，可以直接按 zh。
** 目录跳转
| gh | 回到 home |
| g/ | 根目录     |
** 排序
| os | 按大小排序    |
| on | 按文件名排序  |
| ot | 按修改时间排序 |
| oe | 按扩展名排序  |
** 其他
| : | 输入 lf 命令           |
| ! | 执行 shell 命令        |
| $ | 执行 shell 命令并等待    |
| % | 执行 shell 命令并保持 lf |
| q | 退出                  |
* 清理
** sudo nix-env --profile /nix/var/nix/profiles/system --delete-generations +3
- 作用是：删除 NixOS system profile 中的旧 generation 引用,开机显示
- 这里的关键是：删除 generation 记录/引用，不等于马上删除 /nix/store 里的文件。
- 所以执行完后，旧 generation 所依赖的 store path 可能仍然存在。
** sudo nh clean all
作用是：清理已经没有任何有效引用的 /nix/store 内容
* 安裝中文輸入法fcitx5
在~/.xinitx里添加
#+begin_example
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus

fcitx5 -d
#+end_example
在configuration.nix里添加
#+begin_example
  i18n = {
    defaultLocale = "en_US.UTF-8";

    supportedLocales = [
      "en_US.UTF-8/UTF-8"
      "zh_CN.UTF-8/UTF-8"
    ];
    inputMethod = {
      enable = true;
      type = "fcitx5";

      fcitx5.addons = with pkgs; [
        rime-data
        fcitx5-gtk
        fcitx5-nord
        fcitx5-rime
      ];
    };
  };
#+end_example
另外重要一点，不能在
environment.systemPackages = with pkgs; [  ] 里添加fcitx5
重啓後，輸入法配置里增加rime即可
* 更新app
#+begin_src C
  先进入nixos的配置文件目录，比如~/Download/nixos
  nix flake update
  git add .                      //上传git修改
  git commit
  git push
  nh os switch
#+end_src
* 机场代理有问题，离线模式先能更新系统配置
#+begin_src C
sudo nixos-rebuild switch --flake .#主机名 --offline
主机名可以hostname 查看
#+end_src
* xprop输出的class
#+begin_src C
WM_CLASS = "com.follow.clash", "Com.follow.clash"
                           ↑                    ↑
                        instance             class
即第一个是instance,第二个是clash
awesomewm的rule里，比如
{
    rule_any = {
        instance = { "com.follow.clash" },
    },
    properties = {
        screen = 1,
        tag = "⒍",
        switch_to_tags = false,
        placement = awful.placement.centered,
    },
},
如下两者都能用
instance = { "com.follow.clash" }
class    = { "Com.follow.clash" }
#+end_src
* NixOS 安装 ISO 默认可以通过 SSH 登录
** 假设：
- Win10：SSH 客户端
- NixOS ISO：被连接的机器
- NixOS ISO 已经联网
** 在 NixOS ISO 终端执行： sudo systemctl start sshd
** 然后查看 ISO 的 IP： ip addr
** 例如看到： inet 192.168.1.100/24
** 那么 Win10 上执行： ssh nixos@192.168.1.100
** 不过有一个关键点：ISO 环境里的 nixos 用户通常没有可用密码，所以需要先设置密码： sudo passwd nixos 然后输入密码。
** 因此完整流程就是：
#+begin_src C
sudo systemctl start sshd
sudo passwd nixos
ip addr
#+end_src
** Win10： ssh nixos@192.168.1.100
** 如果提示： The authenticity of host ... can't be established.
输入： yes 即可。
** 如果你是在安装 NixOS 时使用 SSH，我更推荐直接在 ISO 上运行：
#+begin_src C
sudo systemctl enable --now sshd
sudo passwd nixos
#+end_src
** 这样 SSH 服务立即启动，同时设置为当前运行环境的启用状态。
** 注意：ISO 重启后这些设置都会消失，因为你修改的是 live ISO 的运行环境，不是最终安装到硬盘的 NixOS。
* 装nixos系统
** vmware须设置uefi模式启动
** 进入iso系统后,使用root且设置密码，以便ssh登录
#+begin_src C
  sudo -i
  passwd root
#+end_src
** 用fdisk分区,且格式化
*** 用fdisk分区
**** 分区1 1G大小，fdisk里选类型1 即efi类型
**** 分区2 设置2倍ram大小，fdisk里选类型19  即swap类型
**** 分区3 设置剩下的所有磁盘空间大小，fdisk里选类型23  即linux-root类型
**** 按p查看所有分区信息
**** 最后按w写入并生效所有设置后退出fdisk
*** 格式化
           - 分区1 mkfs.fat -F32 /dev/sda1
           - 分区2 mkswap /dev/sda2
           - 分区3 mkfs.ext4 /dev/sda3
*** 挂载,须如下顺序
#+begin_src C
mount /dev/sda3 /mnt
mount --mkdir /dev/sda2 /mnt/boot
swapon /dev/sda2
#+end_src
** iso系统开启ssh
#+begin_src C
systemctl start sshd
ip addr
#+end_src
** 其他系统里登录iso
#+begin_src C
ssh root@192.168.0.103
#+end_src
** 第一次登录正常，后面登录失败，试试 ssh-keygen -R 192.168.0.103  后再登录
** 将如下基本configuration.nix文件用scp传给iso
#+begin_src C
  { config, lib, pkgs,  ... }:
  {
    imports =
      [
        ./hardware-configuration.nix
      ];

    boot.loader.systemd-boot.enable = true;
    boot.loader.efi.canTouchEfiVariables = true;
    boot.loader.timeout = 3;
    boot.consoleLogLevel = 0;
    boot.initrd.verbose = false;
    boot.kernelParams = [
      "quiet"
      "loglevel=3"
      "systemd.show_status=false"
      "rd.systemd.show_status=false"
      "udev.log_level=3"
    ];
    boot.kernelPackages = pkgs.linuxPackages_latest;

    system.stateVersion = "26.11";
    #nix.settings.experimental-features = ["nix-command" "flakes"];

    nix.settings.substituters = [
      "https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store?priority=5"
      "https://mirrors.ustc.edu.cn/nix-channels/store?priority=10"
      "https://cache.nixos.org/"
    ];

    networking.hostName = "nixos";
    networking.networkmanager.enable = true;
    #networking.proxy.default = "http://127.0.0.1:7890";
    #networking.proxy.noProxy = "127.0.0.1,localhost";
    networking.firewall.enable = false;

    time.timeZone = "Asia/Shanghai";

    environment.systemPackages = with pkgs; [
      vim
 	  nvim
      wget
      curl
      git
      clash-verge-rev
    ];

    environment.variables = {
      EDITOR = "nvim";
      VISUAL = "nvim";
    };

    i18n = {
      defaultLocale = "en_US.UTF-8";

      supportedLocales = [
        "en_US.UTF-8/UTF-8"
        "zh_CN.UTF-8/UTF-8"
      ];
      inputMethod = {
        enable = true;
        type = "fcitx5";

        fcitx5.addons = with pkgs; [
          rime-data
          fcitx5-gtk
          fcitx5-nord
          fcitx5-rime
        ];
      };
    };

    programs.fuse.userAllowOther = true;
    #programs.thunar.enable = true;
    programs.fish.enable = true;
    programs.dconf.enable = true;
    #programs.nix-ld.enable = true;
    #programs.nix-ld.libraries = with pkgs; [
    #  gcc.cc.lib
    #  freetype
    #  libSM
    #  libICE
    #  libXrender
    #  libXrandr
    #  libXfixes
    #  libXcursor
    #  fontconfig
    #  libX11
    #];

    fonts.packages = with pkgs; [
      nerd-fonts.fira-code
      nerd-fonts.victor-mono
      wqy_zenhei
      noto-fonts-color-emoji
      source-han-sans
      source-han-serif
      lxgw-wenkai
    ];

    fonts.fontconfig.enable = true;
    fonts.fontconfig.defaultFonts = {
      monospace = [ "Victor Mono Nerd Font Mono" ];

      # sansSerif = [ "WenQuanYi Zen Hei" ];
      # sansSerif = [ "Source Han Sans SC" ];
      sansSerif = [ "LXGW WenKai" ];

      # serif = [ "WenQuanYi Zen Hei" ];
      # serif = [ "LXGW WenKai" ];
      serif = [ "Source Han Serif SC" ];
    };
    # Enable the X11 windowing system.
    services.xserver = {
      enable = true;
      windowManager.awesome.enable = true;
      displayManager.startx = {
        enable = true;
        generateScript = true;
      };
    };
    services.gvfs.enable = true;
    services.tumbler.enable = true;
    services.openssh = {
      enable = true;
      settings = {
        PermitRootLogin = "no";
        PasswordAuthentication = true;
      };
    };
    # 解决jlink的usb权限
    services.udev.extraRules = ''
      ATTR{idVendor}=="1366", MODE="0666"
    '';
    services.getty.autologinUser = null;

    virtualisation.vmware.guest.enable = true;
    systemd.services.vmware-hgfs = {
      description = "Mount VMware HGFS";
      after = [ "vmtoolsd.service" ];
      wantedBy = [ "multi-user.target" ];

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${pkgs.open-vm-tools}/bin/vmhgfs-fuse .host:/ /mnt/hgfs -o allow_other";
        ExecStop = "/run/current-system/sw/bin/umount /mnt/hgfs";
      };
    };
    systemd.tmpfiles.rules = [
      "d /mnt/hgfs 0755 root root -"
    ];

    users.users.microvee = {
      isNormalUser = true;
      shell = pkgs.fish;
      extraGroups = [ "wheel" ]; # Enable ‘sudo’ for the user.
    };
    security.sudo.extraRules = [
      {
        users = [ "microvee" ];
        commands = [
          {
            command = "ALL";
            options = [ "NOPASSWD" ];
          }
        ];
      }
    ];
  }
#+end_src
** 比如这样传
#+begin_src C
  scp /path/configuration.nix root@192.168.0.103:/mnt/etc/nixos
  如果目录用scp -r
#+end_src
** 修改iso的nix-chananel为国内源
#+begin_src C
nix-channel --remove nixos
nix-channel --add https://mirrors.ustc.edu.cn/nix-channels/nixos-unstable nixos
nix-channel --update
#+end_src
** 可以install
#+begin_src C
nixos-install
快结束时会提示输入root的passwd，如果长时间没有输入，会报错，得重新输入nixos-install安装，所以别走开太久不管，
最后有 installation finished! 即基本最小系统安装ok了
#+end_src
** 重启前记得：
#+begin_src C
umount -R /mnt
#+end_src
** 默认约定配置文件路径 /mnt/nixos//
 - 但可以通过软链接，使用自定义的配置文件，软链到默认配置文件路径即可
** 首次安装没有代理问题
  - 安装用unstable版的clash-verge-rev
  - 先暂时把自己的配置文件的flake.nix和home.nix文件放到其他位置比如/tmp里
  - 用 sudo nixos-rebuild switch --offline 安装unstable版的clash-verge-rev
  - 用scp 传过来代理订阅，后使系统能用上代理，然后将configuration.nix里的flake特性打开，proxy打开
  - 检查 configuration.nix 里的proxy端口和~/.gitconfig里的proxy端口跟代理软件一致后
  - 再sudo nixos-rebuild switch --offline
  - 如果能连代理后，即可起飞
  - 再把flake.nix   home.nix等恢复到配置文件夹里来，相关配置打开，恢复前面删除的inputs -> { config, lib, pkgs, inputs, ... }:
  - 重新sudo nixos-rebuild switch
